Repository Talend/components, pull requests merged in 2018-04, with the labels that each got.

#1238 fix(TDI-40301): tAzureStorageQueueOutput duplicate the last data
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/queue/runtime/AzureStorageQueueWriter.java
Labels: Need review

#1239 fix(TDI-40066): prevent api calls is repository is used.
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/SalesforceModuleProperties.java
  components/components-snowflake/src/main/java/org/talend/components/snowflake/SnowflakeTableProperties.java
Labels: Need review

#1240 fix(TDI-40301): add synchronized signature to sendParallelMessages
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/queue/runtime/AzureStorageQueueWriter.java
Labels: Need review

#1243 fix(TDI-40331): add timeout for invalid credentials
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveRuntime.java
  components/components-googledrive/components-googledrive-runtime/src/main/resources/org/talend/components/google/drive/runtime/messages.properties
Labels: Merged build passed, Need review

#1241 fix(TFD-3012): Use deterministic JSON schema inferrer.
  components-parent/pom.xml
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/beamcopy/ConfigurableHDFSFileSink.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/sinks/AvroHdfsFileSink.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/sinks/ParquetHdfsFileSink.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/sinks/UgiFileSinkBase.java
  services/components-api-service-rest-all-components/pom.xml
  services/components-api-service-rest/pom.xml
Labels: Merged build failed

#1242 fix(TDI-40300): add assertion for topology
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/table/tazurestorageoutputtable/TAzureStorageOutputTableDefinition.java
  components/components-azurestorage/src/test/java/org/talend/components/azurestorage/table/AzureStorageTableComponentsTest.java
Labels: Merged build failed, Need review

#1245 fix(TDI-40301): move synchronized block to fix concurrent access
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/queue/runtime/AzureStorageQueueWriter.java
Labels: Merged build passed, Need review

#1248 fix(TDI-40431): Connection to salesforce is failing
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/SalesforceConnectionProperties.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/dataprep/SalesforceDataprepSource.java
Labels: Need review

#1249 fix(TFD-4213): Connection to salesforce is failing
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/SalesforceConnectionProperties.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/dataprep/SalesforceDataprepSource.java
Labels: Merged build passed

#1254 fix(TDI-40431): salesforce endpoint migration for old job
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/SalesforceConnectionProperties.java
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/migration/SalesforceInputPropertiesMigrationTaskTest.java
Labels: Need review

#1253 fix(rskraba): Don't write files for empty streaming panes.
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/beamcopy/ConfigurableHDFSFileSink.java
Labels: Merged build passed

#1247 fix(TFD-3915): Set field selectors to 100 maxItems.
  components/components-processing/processing-definition/src/main/java/org/talend/components/processing/definition/fieldselector/FieldSelectorProperties.java
Labels: Merged build passed

#1258 fix(TDI-40300): fix missing connector warning
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/table/tazurestorageoutputtable/TAzureStorageOutputTableDefinition.java
  components/components-azurestorage/src/test/java/org/talend/components/azurestorage/table/AzureStorageTableComponentsTest.java
Labels: Need review

#1140 chore(TDI-39921): Extend Integration tests for GoogleDrive
  components/components-googledrive/components-googledrive-integration/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveBaseTestIT.java
  components/components-googledrive/components-googledrive-integration/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveCopyTestIT.java
  components/components-googledrive/components-googledrive-integration/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveCreateDeleteTestIT.java
  components/components-googledrive/components-googledrive-integration/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveDatasetTestIT.java
  components/components-googledrive/components-googledrive-integration/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveListTestIT.java
  components/components-googledrive/components-googledrive-integration/src/test/java/org/talend/components/google/drive/runtime/GoogleDrivePutGetTestIT.java
  components/components-googledrive/components-googledrive-runtime/src/test/java/org/talend/components/google/drive/runtime/data/GoogleDriveDataSourceTest.java
  components/components-googledrive/pom.xml
Labels: Merged build passed
