Repository Talend/components, pull requests merged in 2018-05, with the labels that each got.

#1257 feat(TFD-2816): support python security
  components/components-processing/processing-runtime/pom.xml
  components/components-processing/processing-runtime/src/main/java/org/talend/components/processing/runtime/pythonrow/PythonRowDoFn.java
  components/components-processing/processing-runtime/src/main/resources/org/talend/components/processing/runtime/pythonrow/deny.security.abs.policy
  components/components-processing/processing-runtime/src/test/java/org/talend/components/processing/runtime/pythonrow/PythonRowDoFnSecurityTest.java
Labels: Merged build passed

#1252 feat(TDI-40311): Marketo Datastore Dataset
  components/components-marketo/components-marketo-definition/pom.xml
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/MarketoComponentDefinition.java
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/MarketoFamilyDefinition.java
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/data/MarketoDatasetDefinition.java
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/data/MarketoDatasetProperties.java
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/data/MarketoDatastoreDefinition.java
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/data/MarketoInputDefinition.java
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/data/MarketoInputProperties.java
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/tmarketoconnection/TMarketoConnectionProperties.java
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/data/MarketoDataset_icon32.png
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/data/MarketoDatastore_icon32.png
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/data/messages.properties
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/helpers/CompoundKeyTable.properties
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/helpers/IncludeExcludeTypesTable.properties
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/helpers/MarketoColumnMappingsTable.properties
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/tmarketobulkexec/messages.properties
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/tmarketoconnection/messages.properties
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/tmarketoinput/messages.properties
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/tmarketolistoperation/messages.properties
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/tmarketooutput/messages.properties
  components/components-marketo/components-marketo-definition/src/test/java/org/talend/components/marketo/MarketoFamilyDefinitionTest.java
  components/components-marketo/components-marketo-definition/src/test/java/org/talend/components/marketo/MarketoTestBase.java
  components/components-marketo/components-marketo-definition/src/test/java/org/talend/components/marketo/data/MarketoDatasetDefinitionTest.java
  components/components-marketo/components-marketo-definition/src/test/java/org/talend/components/marketo/data/MarketoDatasetPropertiesTest.java
  components/components-marketo/components-marketo-definition/src/test/java/org/talend/components/marketo/data/MarketoDatastoreDefinitionTest.java
  components/components-marketo/components-marketo-definition/src/test/java/org/talend/components/marketo/data/MarketoInputDefinitionTest.java
  components/components-marketo/components-marketo-definition/src/test/java/org/talend/components/marketo/data/MarketoInputPropertiesTest.java
  components/components-marketo/components-marketo-integration/src/test/java/org/talend/components/marketo/runtime/MarketoDatasetRuntimeTestIT.java
  components/components-marketo/components-marketo-integration/src/test/java/org/talend/components/marketo/runtime/MarketoDatasetSourceTestIT.java
  components/components-marketo/components-marketo-integration/src/test/java/org/talend/components/marketo/runtime/MarketoDatastoreRuntimeTestIT.java
  components/components-marketo/components-marketo-runtime/pom.xml
  components/components-marketo/components-marketo-runtime/src/main/java/org/talend/components/marketo/runtime/client/MarketoBaseRESTClient.java
  components/components-marketo/components-marketo-runtime/src/main/java/org/talend/components/marketo/runtime/client/MarketoBulkExecClient.java
  components/components-marketo/components-marketo-runtime/src/main/java/org/talend/components/marketo/runtime/data/MarketoDatasetRuntime.java
  components/components-marketo/components-marketo-runtime/src/main/java/org/talend/components/marketo/runtime/data/MarketoDatasetSource.java
  components/components-marketo/components-marketo-runtime/src/main/java/org/talend/components/marketo/runtime/data/MarketoDatastoreRuntime.java
  components/components-marketo/components-marketo-runtime/src/test/java/org/talend/components/marketo/runtime/MarketoBulkExecReaderTest.java
  components/components-marketo/components-marketo-runtime/src/test/java/org/talend/components/marketo/runtime/MarketoInputWriterTest.java
  components/components-marketo/components-marketo-runtime/src/test/java/org/talend/components/marketo/runtime/MarketoListOperationWriterTest.java
  components/components-marketo/components-marketo-runtime/src/test/java/org/talend/components/marketo/runtime/MarketoOutputWriterTest.java
  components/components-marketo/components-marketo-runtime/src/test/java/org/talend/components/marketo/runtime/MarketoRuntimeTestBase.java
  components/components-marketo/components-marketo-runtime/src/test/java/org/talend/components/marketo/runtime/client/MarketoBaseRESTClientTest.java
  components/components-marketo/components-marketo-runtime/src/test/java/org/talend/components/marketo/runtime/client/MarketoBulkExecClientTest.java
  components/components-marketo/components-marketo-runtime/src/test/java/org/talend/components/marketo/runtime/client/MarketoLeadClientTest.java
  components/components-marketo/components-marketo-runtime/src/test/java/org/talend/components/marketo/runtime/client/rest/type/LeadActivityRecordTest.java
  components/components-marketo/components-marketo-runtime/src/test/java/org/talend/components/marketo/runtime/client/rest/type/LeadChangeRecordTest.java
  components/components-marketo/components-marketo-runtime/src/test/java/org/talend/components/marketo/runtime/data/MarketoDatasetRuntimeTest.java
  components/components-marketo/components-marketo-runtime/src/test/java/org/talend/components/marketo/runtime/data/MarketoDatasetSourceTest.java
  components/components-marketo/components-marketo-runtime/src/test/java/org/talend/components/marketo/runtime/data/MarketoDatastoreRuntimeTest.java
  components/components-marketo/components-marketo-runtime/src/test/resources/customobjects.csv
  components/components-marketo/components-marketo-runtime/src/test/resources/leads.csv
  components/components-marketo/components-marketo-runtime/src/test/resources/log4j.properties
Labels: Merged build passed, Need review

#1263 fix(TDI-40443): add check to control tsalesforceinput bulk mode all return null for empty value
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforceinput/TSalesforceInputProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/tsalesforceinput/messages.properties
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceInputReaderTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/BulkResultAdapterFactory.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSchemaConstants.java
Labels: Merged build passed, Need review

#1267 feat(TDI-40505): integrate Marketo into components-maven-repo
  services/components-maven-repo/pom.xml
Labels: Merged build passed, Need review

#1269 fix(TBD-6957) CVE exclude jasper runtime
  components/components-hadoopcluster/hadoopcluster-runtime/pom.xml
Labels: Merged build passed

#1199 fix(TDI-40107): show all buckets whatever region they are in and remove the region properties, fetch the region by the bucket name at runtime
  components/components-fileio/s3-runtime-di/pom.xml
  components/components-fileio/s3-runtime-di/src/main/java/org/talend/components/s3/runtime/S3Connection.java
  components/components-fileio/s3-runtime-di/src/test/java/org/talend/components/s3/runtime/PropertiesPreparer.java
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/s3/S3DatasetProperties.java
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/s3/S3Region.java
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/s3/S3RegionUtil.java
  components/components-fileio/simplefileio-definition/src/test/java/org/talend/components/simplefileio/s3/S3DatasetPropertiesTest.java
  components/components-fileio/simplefileio-runtime/pom.xml
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/s3/S3Connection.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/s3/S3DatasetRuntime.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/s3/S3DatasetRuntimeTestIT.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/s3/S3TestResource.java
Labels: Merged build passed, Need review

#1272 fix(TFD-4346): security manager not working in concurrency
  components/components-processing/processing-runtime/pom.xml
  components/components-processing/processing-runtime/src/main/java/org/talend/components/processing/runtime/pythonrow/PythonRowDoFn.java
  components/components-processing/processing-runtime/src/main/resources/org/talend/components/processing/runtime/pythonrow/deny.security.abs.policy
  components/components-processing/processing-runtime/src/main/resources/org/talend/components/processing/runtime/pythonrow/import_restriction.py
  components/components-processing/processing-runtime/src/test/java/org/talend/components/processing/runtime/pythonrow/PythonRowDoFnSecurityTest.java
Labels: Merged build passed

#1274 fix(TDI-40311): marketo fix for data-catalog
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/data/MarketoDatasetDefinition.java
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/data/MarketoDatasetProperties.java
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/data/MarketoDatastoreDefinition.java
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/data/MarketoDatastoreProperties.java
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/tmarketoconnection/TMarketoConnectionProperties.java
  components/components-marketo/components-marketo-definition/src/test/java/org/talend/components/marketo/data/MarketoDatasetDefinitionTest.java
  components/components-marketo/components-marketo-definition/src/test/java/org/talend/components/marketo/data/MarketoDatasetPropertiesTest.java
  components/components-marketo/components-marketo-definition/src/test/java/org/talend/components/marketo/data/MarketoDatastoreDefinitionTest.java
  components/components-marketo/components-marketo-definition/src/test/java/org/talend/components/marketo/data/MarketoInputPropertiesTest.java
  components/components-marketo/components-marketo-integration/src/test/java/org/talend/components/marketo/runtime/MarketoDatasetRuntimeTestIT.java
  components/components-marketo/components-marketo-integration/src/test/java/org/talend/components/marketo/runtime/MarketoDatasetSourceTestIT.java
  components/components-marketo/components-marketo-integration/src/test/java/org/talend/components/marketo/runtime/MarketoDatastoreRuntimeTestIT.java
  components/components-marketo/components-marketo-runtime/src/main/java/org/talend/components/marketo/runtime/data/MarketoDatastoreRuntime.java
  components/components-marketo/components-marketo-runtime/src/test/java/org/talend/components/marketo/runtime/data/MarketoDatasetRuntimeTest.java
  components/components-marketo/components-marketo-runtime/src/test/java/org/talend/components/marketo/runtime/data/MarketoDatasetSourceTest.java
  components/components-marketo/components-marketo-runtime/src/test/java/org/talend/components/marketo/runtime/data/MarketoDatastoreRuntimeTest.java
Labels: Merged build passed, Need review

#1275 fix(TFD-4346): fix syntax issue when empty user code
  components/components-processing/processing-runtime/src/main/java/org/talend/components/processing/runtime/pythonrow/PythonRowDoFn.java
  components/components-processing/processing-runtime/src/test/java/org/talend/components/processing/runtime/pythonrow/PythonRowDoFnSecurityTest.java
Labels: Merged build passed

#1278 fix(TDI-40547): remove marketo component from Datastreams
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/data/MarketoDatasetProperties.java
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/data/MarketoInputDefinition.java
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/data/MarketoDatasetProperties.properties
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/data/MarketoDatastoreProperties.properties
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/data/MarketoInputProperties.properties
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/data/messages.properties
  components/components-marketo/components-marketo-definition/src/test/java/org/talend/components/marketo/data/MarketoInputDefinitionTest.java
Labels: Merged build passed, Need review

#1280 fix(TDI-40549): fix and align missing jars for marklogic runtime
  components-parent/components-bom/pom.xml
  components/components-marklogic/components-marklogic-runtime/pom.xml
Labels: Can be merged, Merged build passed

#1266 Mbasiuk/tdi 39565 dynamic schema snowflake
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeGuessSchemaProperties.java
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeRuntimeSourceOrSink.java
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/tsnowflakeinput/TSnowflakeInputProperties.java
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/tsnowflakerow/TSnowflakeRowProperties.java
  components/components-snowflake/components-snowflake-definition/src/main/resources/org/talend/components/snowflake/tsnowflakeinput/messages.properties
  components/components-snowflake/components-snowflake-definition/src/main/resources/org/talend/components/snowflake/tsnowflakerow/messages.properties
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeReadersTestIT.java
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeRowTestIT.java
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeTestIT.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeReader.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeResultSetIndexedRecordConverter.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeRowReader.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeRowWriter.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeSourceOrSink.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/utils/SchemaResolver.java
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/SnowflakeReaderTest.java
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/SnowflakeRowReaderTest.java
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/SnowflakeRowWriterTest.java
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/SnowflakeWriterTest.java
  components/components-snowflake/src/main/java/org/talend/components/snowflake/SnowflakeGuessSchemaProperties.java
  components/components-snowflake/src/main/java/org/talend/components/snowflake/runtime/utils/SchemaResolver.java
  components/components-snowflake/src/test/java/org/talend/components/snowflake/test/SnowflakeRowTestIT.java
Labels: Merged build passed, Need review

#1281 fix(TDI-40549): revert exclusions removing, force some deps
  components/components-marklogic/components-marklogic-runtime/pom.xml
Labels: Merged build passed
