Repository Talend/components, pull requests merged in 2018-10, with the labels that each got.

#1388 bug(TDI-41123) : UPSERT is taken into account
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
Labels: Merged build passed

#1380 feat(TDI-40986): Convert empty to null, snowflake
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/tsnowflakeoutput/TSnowflakeOutputProperties.java
  components/components-snowflake/components-snowflake-definition/src/main/resources/org/talend/components/snowflake/tsnowflakeoutput/messages.properties
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
Labels: Merged build passed

#1389 feat(TDI-41015): fix osgi tests for upgraded library
  components/components-couchbase/pom.xml
Labels: Merged build failed

#1386 Align Docker image version with policy
  services/components-api-service-rest-all-components/pom.xml
  services/components-api-service-rest/pom.xml
Labels: Merged build passed

#1392 fix(TDI-41114): add counter for standalone, improve tests
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeRowStandalone.java
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/SnowflakeRowStandaloneTest.java
Labels: Merged build passed, Need review

#1384 feat(TDI-40958): update salesforce api to 43
  components-parent/components-bom/pom.xml
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/SalesforceConnectionProperties.java
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/integration/SalesforceComponentTestIT.java
  components/components-salesforce/components-salesforce-runtime/pom.xml
  components/pom.xml
Labels: Merged build failed, Need review

#1395 chore(TDI41099): use new docker image, update config, save Dockerfile
  components/components-couchbase/pom.xml
  components/components-couchbase/src/test/java/org/talend/components/couchbase/input/CouchbaseInputTestIT.java
  components/components-couchbase/src/test/resources/docker/Dockerfile
  components/components-couchbase/src/test/resources/docker/README.md
  components/components-couchbase/src/test/resources/docker/configure.sh
Labels: Merged build passed, Need review

#1400 Mbasiuk/tdi 41169 change docker image for old couchbase sdk
  components/components-couchbase/pom.xml
  components/components-couchbase/src/test/java/org/talend/components/couchbase/input/CouchbaseInputTestIT.java
  components/components-couchbase/src/test/resources/docker/Dockerfile
  components/components-couchbase/src/test/resources/docker/README.md
  components/components-couchbase/src/test/resources/docker/configure.sh
Labels: Merged build passed, Need review

#1402 feat(TDI-40958): update salesforce default endpoint to 44.0
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/SalesforceConnectionProperties.java
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/integration/SalesforceComponentTestIT.java
Labels: Merged build passed, Need review

#1378 Ovarnavina/tdi 40921 t snowflake row null value with preparedstatement
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/utils/SnowflakePreparedStatementUtils.java
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/utils/SnowflakePreparedStatementUtilsTest.java
Labels: Merged build passed

#1404 chore: upgrade daikon version to 0.26.1
  components-parent/pom.xml
  services/components-api-service-rest-all-components/pom.xml
  services/components-api-service-rest/pom.xml
Labels: Merged build failed

#1403 fix(TDI-41112): upgrade apache commons lang3
  components-parent/components-bom/pom.xml
  core/components-osgi-test/components-osgitest/pom.xml
  examples/components-api-archetypes/input-component-archetype/src/test/resources/projects/archetypeTest/archetype.properties
Labels: Merged build passed, Reviewing

#1406 fix(TDI-41153) : Use Daikon NameUtil to get compatible Avro name
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeAvroRegistry.java
  core/components-common/src/main/java/org/talend/components/common/avro/JDBCAvroRegistry.java
Labels: Merged build passed

#1401 Dsylaiev/tdi 41144 fix getting schema with not nullable columns
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeAvroRegistry.java
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/SnowflakeAvroRegistryTest.java
Labels: Merged build passed

#1410 chore: bump version in archetype too
  examples/components-api-archetypes/input-component-archetype/src/test/resources/projects/archetypeTest/archetype.properties
Labels: Merged build passed
