Repository Talend/components, pull requests merged in 2018-12, with the labels that each got.

#1439 Mbasiuk/tdi 41415 netsuite retry mechanism
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/NetSuiteClientService.java
  components/components-netsuite/components-netsuite-runtime/src/test/java/org/talend/components/netsuite/client/NetSuiteClientServiceTest.java
  components/components-netsuite/components-netsuite-runtime/src/test/java/org/talend/components/netsuite/test/client/TestNetSuiteClientService.java
  components/components-netsuite/components-netsuite-runtime_2014_2/src/main/java/org/talend/components/netsuite/v2014_2/client/NetSuiteClientServiceImpl.java
  components/components-netsuite/components-netsuite-runtime_2016_2/src/main/java/org/talend/components/netsuite/v2016_2/client/NetSuiteClientServiceImpl.java
  components/components-netsuite/components-netsuite-runtime_2016_2/src/test/java/org/talend/components/netsuite/v2016_2/input/NetSuiteSearchInputReaderIT.java
  components/components-netsuite/components-netsuite-runtime_2016_2/src/test/java/org/talend/components/netsuite/v2016_2/output/NetSuiteOutputWriterIT.java
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/java/org/talend/components/netsuite/v2018_2/client/NetSuiteClientServiceImpl.java
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/platform.core.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/test/java/org/talend/components/netsuite/v2018_2/output/NetSuiteOutputWriterIT.java
Labels: Merged build passed

#1440 chore(TDI-41520): fix API inconsistency, xml formatting
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/activities.scheduling.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/activities.schedulingTypes.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/documents.fileCabinet.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/documents.fileCabinetTypes.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/general.communication.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/general.communicationTypes.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/lists.accounting.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/lists.accountingTypes.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/lists.employeeTypes.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/lists.employees.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/lists.marketing.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/lists.marketingTypes.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/lists.relationshipTypes.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/lists.relationships.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/lists.supplyChain.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/lists.supplyChainTypes.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/lists.support.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/lists.supportTypes.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/lists.website.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/lists.websiteTypes.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/platform.common.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/platform.commonTypes.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/platform.core.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/platform.coreTypes.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/platform.faultTypes.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/platform.faults.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/platform.messages.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/setup.customization.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/setup.customizationTypes.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/transactions.bank.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/transactions.bankTypes.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/transactions.customerTypes.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/transactions.customers.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/transactions.demandPlanning.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/transactions.demandPlanningTypes.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/transactions.employeeTypes.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/transactions.employees.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/transactions.financial.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/transactions.financialTypes.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/transactions.general.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/transactions.inventory.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/transactions.inventoryTypes.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/transactions.purchaseTypes.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/transactions.purchases.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/transactions.saleTypes.xsd
  components/components-netsuite/components-netsuite-runtime_2018_2/src/main/resources/wsdl/2018.2/transactions.sales.xsd
Labels: Merged build failed, Need review

#1443 fix(TDI-41534): Upcase table names when checkbox is true
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
Labels: Merged build passed, Need review
