Repository Talend/components, pull requests merged in 2018-08, with the labels that each got.

#1313 feat(TDI-40684) : Support snowflake on Azure
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeConnectionProperties.java
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeRegion.java
  components/components-snowflake/components-snowflake-definition/src/main/resources/org/talend/components/snowflake/SnowflakeConnectionProperties.properties
  components/components-snowflake/components-snowflake-definition/src/test/java/org/talend/components/snowflake/SnowflakeConnectionPropertiesTest.java
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeRowTestIT.java
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeTestIT.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeSourceOrSink.java
Labels: Merged build failed, Need review

#1352 fix(TDI-40793) : Catch SQLException on jdbc setReadOnly call
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JdbcRuntimeUtils.java
Labels: Merged build failed

#1350 fix(TDI-40793) : Catch SQLException on jdbc setReadOnly call
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JdbcRuntimeUtils.java
Labels: Merged build passed

#1349 fix(TDI-40826): Converting null date values
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeAvroRegistry.java
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/SnowflakeAvroRegistryTest.java
Labels: Merged build passed, Need review

#1353 fix(TDI-40795) uncheck set header as default as migration not work
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/SimpleFileIODatasetProperties.java
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/s3/S3DatasetProperties.java
  components/components-fileio/simplefileio-definition/src/test/java/org/talend/components/simplefileio/MigrationTest.java
  components/components-fileio/simplefileio-definition/src/test/java/org/talend/components/simplefileio/SimpleFileIODatasetPropertiesTest.java
  components/components-fileio/simplefileio-definition/src/test/java/org/talend/components/simplefileio/s3/S3DatasetPropertiesTest.java
  components/components-fileio/simplefileio-definition/src/test/resources/org/talend/components/simplefileio/s3dataset_remove_setheaderline_headerline.json
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/SimpleFileIODatasetRuntimeTest.java
Labels: Merged build passed

#1354 feat(TDI-40828): upgrade cxf version to newest one
  components-parent/components-bom/pom.xml
  components-parent/pom.xml
  components/components-netsuite/components-netsuite-runtime/pom.xml
Labels: Merged build failed, Need review

#1359 chore: Update fabric8 docker plugin version.
  components-parent/pom.xml
  services/components-api-service-rest/pom.xml
Labels: Merged build failed

#1357 fix(TFD-4978): Always use a default fetch size for JDBC.
  components/components-jdbc/components-jdbc-runtime-beam/src/main/java/org/talend/components/jdbc/runtime/JDBCInputPTransformRuntime.java
Labels: Merged build passed

#1317 feat(TDI-40669): whitelist sql queries in cloud
  components-parent/components-bom/pom.xml
  components/components-jdbc/components-jdbc-definition/pom.xml
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/CommonUtils.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/validation/CalciteQueryValidator.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/validation/PatternQueryValidator.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/validation/QueryValidator.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/validation/QueryValidatorFactory.java
Labels: Merged build failed, Need review
