Repository Talend/components, pull requests merged in 2018-09, with the labels that each got.

#1366 fix(TFD-5403): Do not set Boolean properties to required.
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/s3/S3DatastoreProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/datastore/JDBCDatastoreDefinition.java
  components/components-jdbc/components-jdbc-definition/src/test/java/org/talend/components/jdbc/datastore/JDBCDatastoreDefinitionTest.java
  components/components-kinesis/kinesis-definition/src/main/java/org/talend/components/kinesis/KinesisDatastoreProperties.java
  components/components-kinesis/kinesis-definition/src/main/java/org/talend/components/kinesis/input/KinesisInputProperties.java
  components/components-kinesis/kinesis-definition/src/test/java/org/talend/components/kinesis/KinesisDatastorePropertiesTest.java
  components/components-kinesis/kinesis-definition/src/test/java/org/talend/components/kinesis/input/KinesisInputPropertiesTest.java
  components/components-localio/localio-definition/src/main/java/org/talend/components/localio/fixed/FixedDatastoreDefinition.java
  components/components-localio/localio-definition/src/test/java/org/talend/components/localio/fixed/FixedDatastoreDefinitionTest.java
Labels: Merged build passed

#1355 Yacarof/feat/tdp 5986 display the url field in salesforce connector
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/datastore/SalesforceDatastoreProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/datastore/messages.properties
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/datastore/messages_fr.properties
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/datastore/messages_ja.properties
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/datastore/SalesforceDatastoreDefinitionTest.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/dataprep/SalesforceDataprepSource.java
  components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/runtime/dataprep/SalesforceDataprepSourceTest.java
Labels: Merged build failed

#1367 fix(TDI-40730):correct english
  components/components-azurestorage/src/main/resources/org/talend/components/azurestorage/blob/runtime/messages.properties
  components/components-azurestorage/src/main/resources/org/talend/components/azurestorage/messages.properties
  components/components-azurestorage/src/main/resources/org/talend/components/azurestorage/queue/runtime/messages.properties
  components/components-azurestorage/src/main/resources/org/talend/components/azurestorage/table/helpers/messages.properties
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/SalesforceBulkProperties.properties
Labels: Merged build passed

#1368 feat(TDI-40957): Upgrade snowflake to latest driver
  components-parent/components-bom/pom.xml
Labels: Merged build failed, Need review

#1371 Igonchar/tdi 41029
  components-parent/components-bom/pom.xml
  components/components-jdbc/components-jdbc-definition/pom.xml
Labels: Merged build failed

#1372 fix(TDI-41022): Marklogic protobuf-java missing jar
  components/components-marklogic/components-marklogic-runtime/pom.xml
Labels: Merged build passed

#1365 feat(TDI-40535): track application in snowflake
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeConnectionProperties.java
  components/components-snowflake/components-snowflake-definition/src/test/java/org/talend/components/snowflake/SnowflakeConnectionPropertiesTest.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeRuntime.java
Labels: Merged build failed

#1370 fix(TDI-40961): Fix hardcoded user agent value
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/AzureStorageDefinition.java
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/blob/runtime/AzureStorageRuntime.java
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/blob/runtime/AzureStorageSourceOrSink.java
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/utils/AzureStorageUtils.java
Labels: Merged build passed

#1379 Undx/tdi 41033 marklogic tuj missing jar
  components/components-marklogic/components-marklogic-runtime/pom.xml
Labels: Merged build passed

#1382 feat(TDI-41015): upgrade version, raise default timeout
  components/components-couchbase/pom.xml
  components/components-couchbase/src/main/java/org/talend/components/couchbase/runtime/CouchbaseConnection.java
  components/components-couchbase/src/main/java/org/talend/components/couchbase/runtime/CouchbaseStreamingConnection.java
  components/components-couchbase/src/test/java/org/talend/components/couchbase/runtime/CouchbaseConnectionTest.java
Labels: Merged build failed, Need review

#1383 feat(TDI-40999): Dynamic field for tSnowflakeOB
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
Labels: Merged build passed, Need review

#1385 chore: Let some build which randomly failed run at last
  components/pom.xml
Labels: Merged build failed, Need review

#1377 Ypiel/tdi 40568 snowflake action on table impl rebased
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeTableProperties.java
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/tsnowflakeoutput/TSnowflakeOutputProperties.java
  components/components-snowflake/components-snowflake-definition/src/main/resources/org/talend/components/snowflake/tsnowflakeoutput/messages.properties
  components/components-snowflake/components-snowflake-definition/src/test/java/org/talend/components/snowflake/tsnowflakeoutput/TSnowflakeOutputPropertiesTest.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeSourceOrSink.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/tableaction/SnowflakeTableActionConfig.java
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/SnowflakeReaderTest.java
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/SnowflakeWriterTest.java
  core/components-common/src/main/java/org/talend/components/common/tableaction/ConvertAvroTypeToSQL.java
  core/components-common/src/main/java/org/talend/components/common/tableaction/DefaultSQLClearTableAction.java
  core/components-common/src/main/java/org/talend/components/common/tableaction/DefaultSQLCreateTableAction.java
  core/components-common/src/main/java/org/talend/components/common/tableaction/DefaultSQLTruncateTableAction.java
  core/components-common/src/main/java/org/talend/components/common/tableaction/NoAction.java
  core/components-common/src/main/java/org/talend/components/common/tableaction/TableAction.java
  core/components-common/src/main/java/org/talend/components/common/tableaction/TableActionConfig.java
  core/components-common/src/main/java/org/talend/components/common/tableaction/TableActionManager.java
  core/components-common/src/test/java/org/talend/components/common/tableaction/ConvertAvroTypeToSQLTest.java
  core/components-common/src/test/java/org/talend/components/common/tableaction/DefaultSQLClearTableActionTest.java
  core/components-common/src/test/java/org/talend/components/common/tableaction/DefaultSQLCreateTableActionTest.java
  core/components-common/src/test/java/org/talend/components/common/tableaction/DefaultSQLTruncateTableActionTest.java
  core/components-common/src/test/java/org/talend/components/common/tableaction/NoActionTest.java
  core/components-common/src/test/java/org/talend/components/common/tableaction/TableActionManagerTest.java
  core/components-common/src/test/java/org/talend/components/common/tableaction/TableActionTest.java
  services/components-api-service-rest/src/test/resources/application.properties
Labels: Merged build failed
