Repository Talend/components, pull requests merged in 2018-07, with the labels that each got.

#1295 fix(TDI-37641): add ID field for Update and Delete actions
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputDefinition.java
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputProperties.java
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputDefinitionTest.java
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputPropertiesTest.java
Labels: Merged build passed, Need review

#1309 fix(TCOMP-896): fix the "java.lang.OutOfMemoryError: Requested array size exceeds VM limit" issue, which is caused by Sample get which is not necessary in my opinion.
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/SimpleFileIODatasetRuntime.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/s3/S3DatasetRuntime.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/SimpleFileIODatasetRuntimeTest.java
Labels: Merged build passed

#1318 fix(TDI-40701): S3 component have a different behavior with new param "Set header"
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/SimpleFileIODatasetProperties.java
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/s3/S3DatasetProperties.java
  components/components-fileio/simplefileio-definition/src/test/java/org/talend/components/simplefileio/MigrationTest.java
  components/components-fileio/simplefileio-definition/src/test/resources/org/talend/components/simplefileio/s3dataset_remove_setheaderline_headerline.json
Labels: Merged build passed

#1311 chore(TDI-40648): change jvm property to correct one
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/NetSuiteClientService.java
Labels: Merged build passed, Need review

#1316 fix(TFD-4863/TFD-4864): PubSub credentials/topic operation issues
  components/components-pubsub/pubsub-runtime/src/main/java/org/talend/components/pubsub/runtime/PubSubClient.java
  components/components-pubsub/pubsub-runtime/src/main/java/org/talend/components/pubsub/runtime/PubSubConnection.java
  components/components-pubsub/pubsub-runtime/src/main/java/org/talend/components/pubsub/runtime/PubSubInputRuntime.java
  components/components-pubsub/pubsub-runtime/src/main/java/org/talend/components/pubsub/runtime/PubSubOutputRuntime.java
  components/components-pubsub/pubsub-runtime/src/test/java/org/talend/components/pubsub/runtime/PubSubOutputRuntimeTestIT.java
Labels: Merged build passed

#1310 Mbasiuk/tdi 40648 netsuite improve tests
  components/components-netsuite/components-netsuite-definition/src/main/java/org/talend/components/netsuite/NetSuiteModuleProperties.java
  components/components-netsuite/components-netsuite-definition/src/main/java/org/talend/components/netsuite/NetSuiteProvideConnectionProperties.java
  components/components-netsuite/components-netsuite-definition/src/main/java/org/talend/components/netsuite/NetSuiteRuntime.java
  components/components-netsuite/components-netsuite-definition/src/main/java/org/talend/components/netsuite/connection/NetSuiteConnectionProperties.java
  components/components-netsuite/components-netsuite-definition/src/main/java/org/talend/components/netsuite/input/NetSuiteInputProperties.java
  components/components-netsuite/components-netsuite-definition/src/main/java/org/talend/components/netsuite/output/NetSuiteOutputProperties.java
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/AbstractNetSuiteRuntime.java
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/NetSuiteEndpoint.java
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/NetSuiteSourceOrSink.java
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/NetSuiteClientService.java
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/input/NetSuiteSearchInputReader.java
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/output/NetSuiteOutputWriter.java
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/output/NetSuiteWriteOperation.java
  components/components-netsuite/components-netsuite-runtime/src/main/resources/org/talend/components/netsuite/NetSuiteRuntimeI18n.properties
  components/components-netsuite/components-netsuite-runtime/src/test/java/org/talend/components/netsuite/AbstractNetSuiteTestBase.java
  components/components-netsuite/components-netsuite-runtime_2014_2/src/test/java/org/talend/components/netsuite/v2014_2/client/NetSuiteClientServiceIT.java
  components/components-netsuite/components-netsuite-runtime_2014_2/src/test/java/org/talend/components/netsuite/v2014_2/input/NetSuiteSearchInputReaderIT.java
  components/components-netsuite/components-netsuite-runtime_2014_2/src/test/java/org/talend/components/netsuite/v2014_2/input/NetSuiteSearchInputReaderTest.java
  components/components-netsuite/components-netsuite-runtime_2014_2/src/test/java/org/talend/components/netsuite/v2014_2/input/NsObjectInputTransducerIT.java
  components/components-netsuite/components-netsuite-runtime_2014_2/src/test/java/org/talend/components/netsuite/v2014_2/output/NetSuiteOutputWriterTest.java
  components/components-netsuite/components-netsuite-runtime_2016_2/src/test/java/org/talend/components/netsuite/v2016_2/client/NetSuiteClientServiceIT.java
  components/components-netsuite/components-netsuite-runtime_2016_2/src/test/java/org/talend/components/netsuite/v2016_2/input/NetSuiteSearchInputReaderIT.java
  components/components-netsuite/components-netsuite-runtime_2016_2/src/test/java/org/talend/components/netsuite/v2016_2/input/NetSuiteSearchInputReaderTest.java
  components/components-netsuite/components-netsuite-runtime_2016_2/src/test/java/org/talend/components/netsuite/v2016_2/output/NetSuiteOutputWriterIT.java
  components/components-netsuite/components-netsuite-runtime_2016_2/src/test/java/org/talend/components/netsuite/v2016_2/output/NetSuiteOutputWriterTest.java
Labels: Merged build passed, Need review

#1325 fix(TDI-40692): fix public storage creation
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/blob/AzureStorageBlobService.java
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/blob/runtime/AzureStorageContainerCreateRuntime.java
  components/components-azurestorage/src/test/java/org/talend/components/azurestorage/blob/runtime/AzureStorageContainerCreateRuntimeTest.java
Labels: Merged build passed

#1320 fix(TDI-40721): fix batchmode issue
  components/components-marketo/components-marketo-runtime/src/main/java/org/talend/components/marketo/runtime/MarketoListOperationWriter.java
  components/components-marketo/components-marketo-runtime/src/main/java/org/talend/components/marketo/runtime/MarketoWriter.java
Labels: Merged build passed

#1292 feat(TDI-40559): Set user agent for azurestorage components
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/blob/AzureStorageBlobService.java
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/queue/AzureStorageQueueService.java
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/table/AzureStorageTableService.java
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/utils/AzureStorageUtils.java
Labels: Merged build passed, Need review

#1329 fix(jdbc-runtime): Use a limit to fetch the JDBC dataset sample, in order to avoid memory issue
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCSource.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JdbcRuntimeUtils.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/dataprep/JDBCDatasetRuntime.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCInputReader.java
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/runtime/JdbcRuntimeUtilsTest.java
Labels: Merged build passed

#1333 fix(TDI-40751): Regain AccessType for sending createNotExist
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/blob/AzureStorageBlobService.java
Labels: Merged build passed

#1335 fix(TDI-40661): fix error key from i18n properties
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/dataprep/SalesforceSchemaUtils.java
Labels: Merged build failed

#1337 chore: Update fabric8 docker plugin to use one version.
  components-parent/pom.xml
  components/components-couchbase/pom.xml
  components/components-elasticsearch/elasticsearch-integration/pom.xml
  components/components-elasticsearch/elasticsearch-runtime_2_4/pom.xml
  components/components-jira/pom.xml
  components/components-kafka/kafka-integration/pom.xml
  components/components-kafka/kafka-runtime/pom.xml
  components/components-kinesis/kinesis-runtime/pom.xml
  components/components-splunk/pom.xml
  services/components-api-service-rest-all-components/pom.xml
  services/components-api-service-rest/pom.xml
Labels: Merged build failed

#1338 fix(TCOMP-931): Add support for Hive
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCSourceOrSink.java
Labels: Need review

#1344 fix(TDI-40765): tsalesforceinput format anytype value in trace fields history module
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceAnyTypeFieldTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SObjectAdapterFactory.java
Labels: Merged build passed, Need review

#1315 feat(TDI-40684) : Snowflake support on Azure backport
  components/components-snowflake/src/main/java/org/talend/components/snowflake/SnowflakeConnectionProperties.java
  components/components-snowflake/src/main/java/org/talend/components/snowflake/SnowflakeRegion.java
  components/components-snowflake/src/main/resources/org/talend/components/snowflake/SnowflakeConnectionProperties.properties
  components/components-snowflake/src/test/java/org/talend/components/snowflake/SnowflakeConnectionPropertiesTest.java
Labels: Merged build failed

#1334 feat(TFD-4542): Upgrade to Beam 2.5
  components-parent/components-bom/pom.xml
  components/components-fileio/simplefileio-runtime/pom.xml
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/beamcopy/ConfigurableHDFSFileSink.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/sources/FileSourceBase.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JdbcRuntimeUtils.java
  components/components-kinesis/kinesis-runtime/src/main/java/org/apache/beam/sdk/io/kinesis/TalendKinesisProvider.java
  components/components-kinesis/kinesis-runtime/src/main/java/org/apache/beam/sdk/io/kinesis/auth/BasicAWSCredentialsProvider.java
  components/components-kinesis/kinesis-runtime/src/test/java/org/talend/components/kinesis/runtime/KinesisDatasetRuntimeTestIT.java
  components/components-kinesis/kinesis-runtime/src/test/java/org/talend/components/kinesis/runtime/KinesisTestConstants.java
  core/components-adapter-beam-parent/pom.xml
Labels: Merged build passed

#1342 feat(TDI-40615): Snowflake on_error configuration
  components-parent/components-bom/pom.xml
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/LoaderIT.java
Labels: Merged build passed, Need review

#1327 feat(TDI-40574): tSnowflakeOB and tSnowflakeBE
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
Labels: Need review

#1346 chore(TFD-4542) : cherry-pick elasticsearch fix
  components-parent/components-bom/pom.xml
  components/components-elasticsearch/elasticsearch-runtime_2_4/src/main/java/org/talend/components/elasticsearch/runtime_2_4/ElasticsearchDatasetRuntime.java
  components/components-elasticsearch/elasticsearch-runtime_2_4/src/main/java/org/talend/components/elasticsearch/runtime_2_4/ElasticsearchInputRuntime.java
  core/components-adapter-beam-parent/pom.xml
Labels: Merged build passed

#1339 fix(TDI-40791): remove timeout property in advanced settings for all …
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/tmarketoconnection/TMarketoConnectionProperties.java
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/messages.properties
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/messages_fr.properties
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/messages_ja.properties
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/tmarketoconnection/messages_ja.properties
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/tmarketoinput/messages.properties
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/tmarketoinput/messages_ja.properties
  components/components-marketo/components-marketo-definition/src/test/java/org/talend/components/marketo/tmarketoinput/TMarketoInputPropertiesTest.java
  components/components-marketo/components-marketo-integration/src/test/java/org/talend/components/marketo/runtime/MarketoOutputWriterTestIT.java
  components/components-marketo/components-marketo-runtime/src/main/java/org/talend/components/marketo/runtime/client/MarketoBaseRESTClient.java
  components/components-marketo/components-marketo-runtime/src/main/java/org/talend/components/marketo/runtime/client/MarketoClient.java
Labels: Merged build passed, Need review

#1347 fix(Kafka): use unique group id to avoid time consuming when rejoin same group, that is happened after upgrade to kafka 1.0 client
  components/components-kafka/kafka-runtime/src/test/java/org/talend/components/kafka/runtime/KafkaAvroBeamRuntimeTestIT.java
  components/components-kafka/kafka-runtime/src/test/java/org/talend/components/kafka/runtime/KafkaCsvBeamRuntimeTestIT.java
Labels: Merged build passed
