Repository Talend/components, pull requests merged in 2018-02, with the labels that each got.

#1147 fix(TDI-40061): A job with tSalesforceInput and tRedshiftInput components when executed in parallel fails in 6.5.1 after migrating from 6.2.1.
  core/components-api/src/main/java/org/talend/components/api/component/runtime/JarRuntimeInfo.java
Labels: Merged build passed

#1150 fix(TDI-39940): add vendor credit, credit memo and invoice to mapping
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/customfield/TransactionBodyCustomFieldAdapter.java
Labels: Can be merged, Merged build passed

#1143 fix(TDI-40005): fix connection issue, fix integration tests.
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSinkTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.java
Labels: Merged build passed, Need review

#1151 fix(TDI-39940): add vendor credit, credit memo and invoice to mapping…
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/customfield/TransactionBodyCustomFieldAdapter.java
Labels: Merged build passed

#1152 feat(TDI-39983): Table names case sensitivity
  components/components-snowflake/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
  components/components-snowflake/src/main/java/org/talend/components/snowflake/tsnowflakeoutput/TSnowflakeOutputProperties.java
  components/components-snowflake/src/main/resources/org/talend/components/snowflake/tsnowflakeoutput/messages.properties
  components/components-snowflake/src/test/java/org/talend/components/snowflake/tsnowflakeoutput/TSnowflakeOutputPropertiesTest.java
Labels: Can be merged

#1146 fix(TDI-39619): add logic to exclude tablename if necessary
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/BulkResultAdapterFactory.java
Labels: Merged build passed, Need review

#1153 feat(TDI-39983): Case sensitivity SnowflakeOutput
  components/components-snowflake/src/main/java/org/talend/components/snowflake/tsnowflakeoutput/TSnowflakeOutputProperties.java
  components/components-snowflake/src/test/java/org/talend/components/snowflake/TestUtils.java
  components/components-snowflake/src/test/java/org/talend/components/snowflake/migration/TSnowflakeOutputMigrationTest.java
  components/components-snowflake/src/test/resources/org/talend/components/snowflake/migration/tSnowflakeOuputProperties.json
Labels: Can be merged

#1155 feat(TDI-39983): Case sensitivity SnowflakeOutput
  components/components-snowflake/src/test/resources/org/talend/components/snowflake/migration/tSnowflakeOuputProperties.json
Labels: Need review

#1160 chore(docker) : add memory and jmx env vars
  services/components-api-service-rest/scripts/start.sh
Labels: Merged build passed

#1148 feat(TFD-2986): Improve the UI of Aggregate components.
  components/components-processing/processing-definition/src/main/java/org/talend/components/processing/definition/aggregate/AggregateProperties.java
  components/components-processing/processing-definition/src/main/resources/org/talend/components/processing/definition/aggregate/AggregateGroupByProperties.properties
  components/components-processing/processing-definition/src/main/resources/org/talend/components/processing/definition/aggregate/AggregateOperationProperties.properties
  components/components-processing/processing-definition/src/main/resources/org/talend/components/processing/definition/aggregate/AggregateProperties.properties
Labels: Merged build passed

#1163 fix(TDI-40055): GoogleDrive launch browser in connection's wizard
  components/components-googledrive/components-googledrive-definition/src/main/java/org/talend/components/google/drive/connection/GoogleDriveConnectionProperties.java
  components/components-googledrive/components-googledrive-runtime/pom.xml
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveRuntime.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveValidator.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/client/AuthorizationCodeInstalledAppTalend.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/client/GoogleDriveCredentialWithInstalledApplication.java
Labels: Merged build passed, Need review

#1166 fix(TDI-40148): Hide connection properties when use existing connection
  components/components-snowflake/src/main/java/org/talend/components/snowflake/SnowflakeConnectionProperties.java
  components/components-snowflake/src/test/java/org/talend/components/snowflake/tsnowflakeinput/TSnowflakeInputPropertiesTest.java
Labels: Merged build passed

#1169 feat(TFD-3751): Change default value on Window.
  components/components-processing/processing-definition/src/main/java/org/talend/components/processing/definition/window/WindowProperties.java
  components/components-processing/processing-definition/src/main/resources/org/talend/components/processing/definition/window/messages.properties
Labels: Merged build passed

#1168 feat(TFD-3756): Add /v0/version endpoint to REST service.
  services/components-api-service-rest/pom.xml
  services/components-api-service-rest/src/main/java/org/talend/components/service/rest/VersionController.java
  services/components-api-service-rest/src/main/java/org/talend/components/service/rest/dto/VersionDto.java
  services/components-api-service-rest/src/main/java/org/talend/components/service/rest/impl/VersionControllerImpl.java
  services/components-api-service-rest/src/test/java/org/talend/components/service/rest/impl/VersionControllerImplTest.java
Labels: Merged build passed
