Repository Talend/components, pull requests merged in 2018-06, with the labels that each got.

#1284 fix(TDI-40371): Change the FileIO HDFS parameters order
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/SimpleFileIODatasetProperties.java
Labels: Merged build passed

#1286 fix(TDI-39964): fix missing jar for datastewardship
  core/components-api/pom.xml
Labels: Merged build passed, Need review

#1285 chore(TDI-40554): bump marklogic libs to latest
  components-parent/components-bom/pom.xml
  components/components-marklogic/components-marklogic-runtime/pom.xml
Labels: Merged build passed

#1297 feat(TFD-4246): Fix error handling on FieldSelector.
  components/components-processing/processing-definition/src/main/java/org/talend/components/processing/definition/ProcessingErrorCode.java
  components/components-processing/processing-runtime/src/main/java/org/talend/components/processing/runtime/fieldselector/FieldSelectorDoFn.java
  components/components-processing/processing-runtime/src/test/java/org/talend/components/processing/runtime/fieldselector/FieldSelectorDoFnTest.java
Labels: Merged build passed

#1300 fix(TDI-38418): fix tests and enable them
  components/components-netsuite/components-netsuite-runtime_2014_2/pom.xml
  components/components-netsuite/components-netsuite-runtime_2014_2/src/test/java/org/talend/components/netsuite/v2014_2/client/NetSuiteClientServiceIT.java
  components/components-netsuite/components-netsuite-runtime_2014_2/src/test/java/org/talend/components/netsuite/v2014_2/input/NetSuiteSearchInputReaderIT.java
  components/components-netsuite/components-netsuite-runtime_2016_2/pom.xml
  components/components-netsuite/components-netsuite-runtime_2016_2/src/test/java/org/talend/components/netsuite/v2016_2/client/NetSuiteClientServiceIT.java
  components/components-netsuite/components-netsuite-runtime_2016_2/src/test/java/org/talend/components/netsuite/v2016_2/output/NetSuiteOutputWriterIT.java
Labels: Merged build failed, Need review

#1302 fix(TDI-40596):tSalesforceOutput upsert return wrong rejected records when using extend insert
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceWriterTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceWriter.java
Labels: Merged build passed, Need review

#1288 feat(TDI-39753):Support for Salesforce Bulk API 2.0
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/SalesforceBulkProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforcebulkexec/TSalesforceBulkExecProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulkexec/TSalesforceOutputBulkExecProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/SalesforceBulkProperties.properties
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforcebulkexec/TSalesforceBulkExecPropertiesTest.java
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforceoutputbulkexec/TSalesforceOutputBulkExecPropertiesTest.java
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceBulkExecReaderTestIT.java
  components/components-salesforce/components-salesforce-runtime/pom.xml
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkExecRuntime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkV2ExecReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSource.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/BulkV2Connection.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/JobInfoV2.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/SalesforceBulkV2Runtime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/error/BulkV2ClientException.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/request/CreateJobRequest.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/request/UpdateJobRequest.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/type/HttpMethod.java
  components/components-salesforce/components-salesforce-runtime/src/main/resources/org/talend/components/salesforce/runtime/SalesforceBulkExecRuntime.properties
  components/components-salesforce/components-salesforce-runtime/src/main/resources/org/talend/components/salesforce/runtime/SalesforceBulkV2ExecReader.properties
  components/components-salesforce/components-salesforce-runtime/src/main/resources/org/talend/components/salesforce/runtime/bulk/v2/BulkV2Connection.properties
  components/components-salesforce/components-salesforce-runtime/src/main/resources/org/talend/components/salesforce/runtime/bulk/v2/SalesforceBulkV2Runtime.properties
Labels: Merged build passed, Need review

#1296 chore(TDI-40591): add components-ee jars to BOM
  components-parent/components-bom/pom.xml
Labels: Merged build passed

#1293 fix(TDI-40461): Implement extended Excel for fileio
  components/components-fileio/fileio-integration/src/test/java/org/talend/components/fileio/integration/SandboxedSimpleFileIODatasetRuntimeTest.java
  components/components-fileio/fileio-integration/src/test/java/org/talend/components/fileio/integration/SimpleFileIODatasetRuntimeTest.java
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/ExcelFormat.java
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/SimpleFileIODatasetProperties.java
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/SimpleFileIOFormat.java
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/local/Constant.java
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/local/EncodingType.java
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/local/LocalFileIODatasetDefinition.java
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/local/LocalFileIODatasetProperties.java
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/local/LocalFileIODatastoreDefinition.java
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/local/LocalFileIODatastoreProperties.java
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/s3/S3DatasetProperties.java
  components/components-fileio/simplefileio-definition/src/main/resources/org/talend/components/simplefileio/SimpleFileIODatasetProperties.properties
  components/components-fileio/simplefileio-definition/src/main/resources/org/talend/components/simplefileio/s3/S3DatasetProperties.properties
  components/components-fileio/simplefileio-definition/src/test/java/org/talend/components/simplefileio/SimpleFileIODatasetPropertiesTest.java
  components/components-fileio/simplefileio-definition/src/test/java/org/talend/components/simplefileio/s3/S3DatasetPropertiesTest.java
  components/components-fileio/simplefileio-definition/src/test/java/org/talend/components/simplefileio/s3/output/S3OutputPropertiesTest.java
  components/components-fileio/simplefileio-runtime/pom.xml
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/SimpleFileIOInputRuntime.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/SimpleRecordFormatCsvIO.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/SimpleRecordFormatExcelIO.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/hadoop/csv/CSVFileInputFormat.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/hadoop/csv/CSVFileRecordReader.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/hadoop/csv/CSVFileSplit.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/hadoop/excel/Excel2007FileRecordReader.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/hadoop/excel/Excel97FileRecordReader.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/hadoop/excel/ExcelFileInputFormat.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/hadoop/excel/ExcelHTMLFileRecordReader.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/hadoop/excel/ExcelHtmlParser.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/hadoop/excel/ExcelUtils.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/hadoop/excel/SimpleValuesContentHandler.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/hadoop/excel/streaming/FilesHelper.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/hadoop/excel/streaming/StreamingReader.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/hadoop/excel/streaming/StreamingSheet.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/hadoop/excel/streaming/StreamingSheetReader.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/hadoop/excel/streaming/StreamingWorkbook.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/hadoop/excel/streaming/StreamingWorkbookReader.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/s3/S3InputRuntime.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/sources/CsvHdfsFileSource.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/sources/ExcelHdfsFileSource.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/CsvExample.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/ExtractCsvRecordTest.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/SimpleFileIODatasetRuntimeTest.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/SimpleFileIOInputRuntimeTest.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/SimpleFileIORoundTripRuntimeTest.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/SparkSimpleFileIOInputRuntimeTestIT.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/gs/GSRoundTripRuntimeTestIT.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/s3/S3RoundTripRuntimeTestIT.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/s3/S3SparkRuntimeTestIT.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/test/RecordSetUtil.java
  components/components-fileio/simplefileio-runtime/src/test/resources/org/talend/components/simplefileio/runtime/basic.xls
  components/components-fileio/simplefileio-runtime/src/test/resources/org/talend/components/simplefileio/runtime/basic.xlsx
  components/components-fileio/simplefileio-runtime/src/test/resources/org/talend/components/simplefileio/runtime/emptyrowexist.xlsx
  components/components-fileio/simplefileio-runtime/src/test/resources/org/talend/components/simplefileio/runtime/sales-force.html
Labels: Merged build passed

#1305 feat(TDI-40650):avoid NPE when migration old salesforce bulkexec jobs
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforcebulkexec/TSalesforceBulkExecProperties.java
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforcebulkexec/TSalesforceBulkExecPropertiesTest.java
Labels: Merged build passed, Need review

#1260 feat(TDI-40427): Duplicate of tSnowflakeOutput
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/tsnowflakeoutput/TSnowflakeOutputDefinition.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeResultListener.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeRuntime.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriteOperation.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
Labels: Merged build passed, Work in progress(do not merge)

#1306 fix(TDI-40654): Excel fileio couldn't extract rightly if header line contain empty cell
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/hadoop/excel/Excel2007FileRecordReader.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/hadoop/excel/Excel97FileRecordReader.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/SimpleFileIODatasetRuntimeTest.java
  components/components-fileio/simplefileio-runtime/src/test/resources/org/talend/components/simplefileio/runtime/emptyfield.xls
  components/components-fileio/simplefileio-runtime/src/test/resources/org/talend/components/simplefileio/runtime/emptyfield.xlsx
Labels: Merged build passed

#1307 Tdi-40661 salesforce error i18n
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/dataprep/SalesforceSchemaUtils.java
  components/components-salesforce/components-salesforce-runtime/src/main/resources/org/talend/components/salesforce/runtime/dataprep/SalesforceSchemaUtils.properties
Labels: Merged build passed
