Repository Talend/components, pull requests merged in 2018-03, with the labels that each got.

#1170 feat(TFD-1765) : add AWS Redshift support to JDBC
  services/components-maven-repo/config/jdbc_config.json
  services/components-maven-repo/pom.xml
Labels: Merged build passed

#1161 feat(TFD-2590) FieldSelector
  components/components-processing/processing-definition/src/main/java/org/talend/components/processing/definition/ProcessingErrorCode.java
  components/components-processing/processing-definition/src/main/java/org/talend/components/processing/definition/ProcessingFamilyDefinition.java
  components/components-processing/processing-definition/src/main/java/org/talend/components/processing/definition/fieldselector/FieldSelectorDefinition.java
  components/components-processing/processing-definition/src/main/java/org/talend/components/processing/definition/fieldselector/FieldSelectorProperties.java
  components/components-processing/processing-definition/src/main/java/org/talend/components/processing/definition/fieldselector/SelectorProperties.java
  components/components-processing/processing-definition/src/main/resources/org/talend/components/processing/definition/fieldselector/FieldSelectorDefinition.properties
  components/components-processing/processing-definition/src/main/resources/org/talend/components/processing/definition/fieldselector/FieldSelector_icon32.png
  components/components-processing/processing-definition/src/main/resources/org/talend/components/processing/definition/fieldselector/messages.properties
  components/components-processing/processing-definition/src/test/java/org/talend/components/processing/definition/fieldselector/FieldSelectorDefinitionTest.java
  components/components-processing/processing-definition/src/test/java/org/talend/components/processing/definition/fieldselector/FieldSelectorPropertiesTest.java
  components/components-processing/processing-runtime/src/main/java/org/talend/components/processing/runtime/fieldselector/FieldSelectorDoFn.java
  components/components-processing/processing-runtime/src/main/java/org/talend/components/processing/runtime/fieldselector/FieldSelectorRuntime.java
  components/components-processing/processing-runtime/src/main/java/org/talend/components/processing/runtime/fieldselector/FieldSelectorUtil.java
  components/components-processing/processing-runtime/src/test/java/org/talend/components/processing/runtime/SampleAvpathSchemas.java
  components/components-processing/processing-runtime/src/test/java/org/talend/components/processing/runtime/fieldselector/FieldSelectorDoFnTest.java
  components/components-processing/processing-runtime/src/test/java/org/talend/components/processing/runtime/fieldselector/FieldSelectorUtilTest.java
Labels: Merged build passed

#1173 fix(TDI-37869): Replace json-simple usage with jackson or json-io libraries in JDBC components
  components/components-jdbc/components-jdbc-definition/pom.xml
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/datastore/JDBCDatastoreProperties.java
  components/components-jdbc/components-jdbc-runtime/pom.xml
Labels: Merged build passed

#1165 fix(TFD-3576): rename Development connection to Custom Data
  components/components-localio/localio-definition/src/main/resources/org/talend/components/localio/fixed/FixedDatasetDefinition.properties
  components/components-localio/localio-definition/src/main/resources/org/talend/components/localio/fixed/FixedDatastoreDefinition.properties
  components/components-localio/localio-definition/src/main/resources/org/talend/components/localio/fixed/FixedInputDefinition.properties
Labels: Merged build passed

#1175 fix(TDI-39385): Show Salesforce GetUpdatedDeleted in wizzard
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforcegetdeleted/TSalesforceGetDeletedDefinition.java
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforcegetupdated/TSalesforceGetUpdatedDefinition.java
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforcegetdeleted/TSalesforceGetDeletedDefinitionTest.java
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforcegetupdated/TSalesforceGetUpdatedDefinitionTest.java
Labels: Merged build passed

#1174 feat(TFD-3728): Add a Limit component
  components/components-processing/processing-definition/src/main/java/org/talend/components/processing/definition/ProcessingFamilyDefinition.java
  components/components-processing/processing-definition/src/main/java/org/talend/components/processing/definition/limit/LimitDefinition.java
  components/components-processing/processing-definition/src/main/java/org/talend/components/processing/definition/limit/LimitProperties.java
  components/components-processing/processing-definition/src/main/resources/org/talend/components/processing/definition/limit/LimitDefinition.properties
  components/components-processing/processing-definition/src/main/resources/org/talend/components/processing/definition/limit/Limit_icon32.png
  components/components-processing/processing-definition/src/main/resources/org/talend/components/processing/definition/limit/messages.properties
  components/components-processing/processing-runtime/src/main/java/org/talend/components/processing/runtime/limit/LimitDoFn.java
  components/components-processing/processing-runtime/src/main/java/org/talend/components/processing/runtime/limit/LimitRuntime.java
  components/components-processing/processing-runtime/src/test/java/org/talend/components/processing/runtime/limit/LimitRuntimeTest.java
Labels: Merged build passed

#1178 chore: We love the FieldSelector component
  components/components-processing/processing-definition/src/main/java/org/talend/components/processing/definition/ProcessingFamilyDefinition.java
Labels: Merged build passed

#1179 chore: bump daikon version to 0.17.3-SNAPSHOT
  components-parent/pom.xml
  services/components-api-service-rest-all-components/pom.xml
  services/components-api-service-rest/pom.xml
Labels: Merged build failed

#1171 fix(TDI-40047): add missing migration for login timeout value
  components/components-snowflake/src/main/java/org/talend/components/snowflake/SnowflakeConnectionProperties.java
  components/components-snowflake/src/test/java/org/talend/components/snowflake/SnowflakeConnectionPropertiesTest.java
Labels: Merged build passed, Need review

#1158 fix(TFD-2647): Add type converter.
  components/components-processing/README.md
  components/components-processing/processing-definition/src/main/java/org/talend/components/processing/definition/ProcessingFamilyDefinition.java
  components/components-processing/processing-definition/src/main/java/org/talend/components/processing/definition/typeconverter/TypeConverterDefinition.java
  components/components-processing/processing-definition/src/main/java/org/talend/components/processing/definition/typeconverter/TypeConverterProperties.java
  components/components-processing/processing-definition/src/test/java/org/talend/components/processing/definition/typeconverter/TypeConverterDefinitionTest.java
  components/components-processing/processing-definition/src/test/java/org/talend/components/processing/definition/typeconverter/TypeConverterPropertiesTest.java
  components/components-processing/processing-runtime/src/main/java/org/talend/components/processing/runtime/aggregate/AggregateCombineFn.java
  components/components-processing/processing-runtime/src/main/java/org/talend/components/processing/runtime/typeconverter/TypeConverterFunction.java
  components/components-processing/processing-runtime/src/main/java/org/talend/components/processing/runtime/typeconverter/TypeConverterRuntime.java
  components/components-processing/processing-runtime/src/main/java/org/talend/components/processing/runtime/typeconverter/TypeConverterUtils.java
  components/components-processing/processing-runtime/src/test/java/org/talend/components/processing/runtime/typeconverter/TypeConverterFunctionTest.java
  components/components-processing/processing-runtime/src/test/java/org/talend/components/processing/runtime/typeconverter/TypeConverterUtilsTest.java
Labels: Merged build passed

#1182 fix(TDI-39944): when tSalesforceOutput write dynamic field didn't pass value to component behind it
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceWriterTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceWriter.java
Labels: Merged build passed, Need review

#1183 fix(TDI-40010): Can't propagate schema to tJDBCOutput
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcoutput/TJDBCOutputDefinition.java
  components/components-jdbc/components-jdbc-definition/src/test/java/org/talend/components/jdbc/tjdbcoutput/TJDBCOutputDefinitionTest.java
Labels: Merged build passed

#1185 fix(TDI-39675): [Salesforce] Filter additional modules not supported by the Bulk API
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/dataset/SalesforceDatasetProperties.java
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/dataset/SalesforceDatasetPropertiesTestIT.java
Labels: Merged build passed

#1184 feat(TDI-40177): Update salesforce API to latest version 42
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/SalesforceConnectionProperties.java
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/integration/SalesforceComponentTestIT.java
  components/components-salesforce/components-salesforce-runtime/pom.xml
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/dataprep/SalesforceDataprepSource.java
Labels: Merged build passed, Need review

#1186 fix(TDI-40198): Salesforce dataprep didn't close the bulk api job
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/dataprep/SalesforceBulkQueryReader.java
Labels: Merged build passed

#1189 feat(TDI-40129) Upgrade to CXF 3.2.2
  components/components-netsuite/components-netsuite-runtime/pom.xml
  components/components-netsuite/components-netsuite-runtime_2014_2/pom.xml
  components/components-netsuite/components-netsuite-runtime_2016_2/pom.xml
Labels: Merged build passed, Need review

#1180 feat(TFD-3799): Infer valide output name on hierarchical values.
  components/components-processing/processing-runtime/src/main/java/org/talend/components/processing/runtime/aggregate/AggregateUtils.java
  components/components-processing/processing-runtime/src/test/java/org/talend/components/processing/runtime/aggregate/AggregateUtilsTest.java
Labels: Merged build passed

#1192 chore: Update TypeConverter spec and rename Input Format to Format.
  components/components-processing/README.md
  components/components-processing/processing-definition/src/main/resources/org/talend/components/processing/definition/typeconverter/messages.properties
Labels: Merged build passed

#1193 feat(TFD-3568): Flatten Kafka datastore to triggers.
  components/components-kafka/kafka-definition/src/main/java/org/talend/components/kafka/datastore/KafkaDatastoreProperties.java
  components/components-kafka/kafka-definition/src/main/resources/org/talend/components/kafka/datastore/KafkaDatastoreProperties.properties
  components/components-kafka/kafka-definition/src/main/resources/org/talend/components/kafka/datastore/KafkaDatastoreProperties_ja.properties
  components/components-kafka/kafka-definition/src/test/java/org/talend/components/kafka/datastore/KafkaDatastorePropertiesTest.java
  components/components-kafka/kafka-runtime/src/main/java/org/talend/components/kafka/runtime/KafkaConnection.java
Labels: Merged build passed

#1196 chore(TFD-3848): add MariaDB in JDBC drivers list
  services/components-maven-repo/config/jdbc_config.json
Labels: Merged build passed

#1197 chore(aggregate): rename label for generated field
  components/components-processing/processing-definition/src/main/resources/org/talend/components/processing/definition/aggregate/AggregateOperationProperties.properties
Labels: Merged build passed

#1132 feat(TFD-3488): upgrade to Beam 2.3
  components-parent/pom.xml
  components/components-bigquery/bigquery-runtime/pom.xml
  components/components-bigquery/bigquery-runtime/src/main/java/org/talend/components/bigquery/runtime/BigQueryDatasetRuntime.java
  components/components-bigquery/bigquery-runtime/src/main/java/org/talend/components/bigquery/runtime/BigQueryDatastoreRuntime.java
  components/components-bigquery/bigquery-runtime/src/main/java/org/talend/components/bigquery/runtime/BigQueryInputRuntime.java
  components/components-bigquery/bigquery-runtime/src/main/java/org/talend/components/bigquery/runtime/BigQueryOutputRuntime.java
  components/components-bigquery/bigquery-runtime/src/test/java/org/talend/components/bigquery/runtime/BigQueryBeamRuntimeTestIT.java
  components/components-elasticsearch/elasticsearch-runtime_2_4/pom.xml
  components/components-elasticsearch/elasticsearch-runtime_2_4/src/main/java/org/talend/components/elasticsearch/runtime_2_4/ElasticsearchInputRuntime.java
  components/components-elasticsearch/elasticsearch-runtime_2_4/src/test/java/org/talend/components/elasticsearch/runtime_2_4/ElasticsearchBeamRuntimeTestIT.java
  components/components-fileio/fileio-integration/pom.xml
  components/components-fileio/simplefileio-runtime/pom.xml
  components/components-jms/jms-runtime_1_1/pom.xml
  components/components-jms/jms-runtime_1_1/src/main/java/org/talend/components/jms/runtime_1_1/JmsInputPTransformRuntime.java
  components/components-kafka/kafka-runtime/src/main/java/org/talend/components/kafka/runtime/KafkaInputPTransformRuntime.java
  components/components-kinesis/kinesis-integration/pom.xml
  components/components-kinesis/kinesis-runtime/pom.xml
  components/components-kinesis/kinesis-runtime/src/main/java/org/apache/beam/sdk/io/kinesis/TalendKinesisProvider.java
  components/components-kinesis/kinesis-runtime/src/main/java/org/talend/components/kinesis/runtime/KinesisClient.java
  components/components-kinesis/kinesis-runtime/src/main/java/org/talend/components/kinesis/runtime/KinesisInputRuntime.java
  components/components-kinesis/kinesis-runtime/src/test/java/org/talend/components/kinesis/runtime/KinesisInputRuntimeTestIT.java
  components/components-processing/processing-runtime/pom.xml
  components/components-processing/processing-runtime/src/main/java/org/talend/components/processing/runtime/aggregate/AggregateCombineFn.java
  components/components-processing/processing-runtime/src/test/java/org/talend/components/processing/runtime/aggregate/AggregateRuntimeTest.java
  components/components-pubsub/pubsub-runtime/pom.xml
  components/components-pubsub/pubsub-runtime/src/test/java/org/talend/components/pubsub/runtime/PubSubInputRuntimeTestIT.java
  components/components-pubsub/pubsub-runtime/src/test/java/org/talend/components/pubsub/runtime/PubSubOutputRuntimeTestIT.java
  core/components-adapter-beam-parent/pom.xml
  core/components-adapter-beam/pom.xml
  core/components-adapter-beam/src/main/java/org/talend/components/adapter/beam/utils/SparkRunnerTestUtils.java
  examples/components-api-archetypes/bd-component-archetype/src/main/resources/archetype-resources/__componentNameLowerCase__-integration/pom.xml
  examples/components-api-archetypes/bd-component-archetype/src/main/resources/archetype-resources/__componentNameLowerCase__-runtime/pom.xml
  services/components-api-service-rest-all-components/pom.xml
  services/components-api-service-rest/pom.xml
  services/components-maven-repo/pom.xml
Labels: Merged build passed

#1203 fix(TFD-3857): PubSub, fix NPE issue for empty topic
  components/components-pubsub/pubsub-runtime/src/main/java/org/talend/components/pubsub/runtime/PubSubInputRuntime.java
  components/components-pubsub/pubsub-runtime/src/test/java/org/talend/components/pubsub/runtime/PubSubDatasetRuntimeTestIT.java
Labels: Merged build passed

#1181 fix(TDC-638): Use an empty schema on CSV file with no record.
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/SimpleFileIODatasetRuntime.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/SimpleFileIODatasetRuntimeTest.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/test/RecordSet.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/test/RecordSetUtil.java
Labels: Merged build passed

#1201 fix(TFD-3854): Ensure that top-level generated records are named.
  core/components-adapter-beam/src/main/java/org/talend/components/adapter/beam/kv/KeyValueRecordConstant.java
  core/components-adapter-beam/src/main/java/org/talend/components/adapter/beam/kv/SchemaGeneratorUtils.java
  core/components-adapter-beam/src/test/java/org/talend/components/adapter/beam/kv/SchemaGeneratorUtilsTest.java
Labels: Merged build passed

#1206 fix(TFD-3799): Return no results from default aggregate properties.
  components/components-processing/processing-runtime/src/main/java/org/talend/components/processing/runtime/aggregate/AggregateRuntime.java
  components/components-processing/processing-runtime/src/test/java/org/talend/components/processing/runtime/aggregate/AggregateRuntimeTest.java
Labels: Merged build passed

#1209 feat(TFD-3880): Limit component - increase limit from 1 million to 10…
  components/components-processing/processing-definition/src/main/java/org/talend/components/processing/definition/limit/LimitProperties.java
Labels: Merged build passed

#1202 fix(TDI-40195): Case sensitivity SnowflakeInput
  components/components-snowflake/src/main/java/org/talend/components/snowflake/runtime/SnowflakeReader.java
  components/components-snowflake/src/main/java/org/talend/components/snowflake/tsnowflakeinput/TSnowflakeInputProperties.java
  components/components-snowflake/src/main/resources/org/talend/components/snowflake/tsnowflakeinput/messages.properties
  components/components-snowflake/src/test/java/org/talend/components/snowflake/TestUtils.java
  components/components-snowflake/src/test/java/org/talend/components/snowflake/migration/TSnowflakeOutputMigrationTest.java
  components/components-snowflake/src/test/java/org/talend/components/snowflake/runtime/SnowflakeReaderTest.java
  components/components-snowflake/src/test/java/org/talend/components/snowflake/tsnowflakeinput/TSnowflakeInputPropertiesTest.java
Labels: Merged build passed

#1210 fix(TFD-3558): Use ui:placeholder for JDBC URL.
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/datastore/JDBCDatastoreProperties.java
  components/components-jdbc/components-jdbc-integration/src/test/java/org/talend/components/jdbc/dataprep/JdbcDatasetTestIT.java
  components/components-jdbc/components-jdbc-integration/src/test/java/org/talend/components/jdbc/dataprep/JdbcInputTestIT.java
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/dataprep/JDBCDatasetTestIT.java
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/dataprep/JDBCInputTestIT.java
Labels: Merged build passed

#1211 fix(TFD-3704): Ensure CSV merges do not loop infinitely.
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/sinks/UgiFileSinkBase.java
Labels: Merged build passed

#1212 fix(TDI-40159) Unable connect to Salesforce via connection type OAuth.
  core/components-common-oauth/pom.xml
Labels: Merged build failed, Need review

#1205 fix(TDI-39990): The Feature 'Guess schema' of tJDBCOutput/Input should have message to hint 'table doesn't exist'
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/CommonUtils.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcinput/TJDBCInputProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcoutput/TJDBCOutputProperties.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/avro/JDBCSPIndexedRecordCreator.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCCloseSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCCommitSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCRollbackSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCRowSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCSPSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JdbcRuntimeUtils.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCInputReader.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCRowReader.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCSPReader.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCCommitWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputDeleteWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputInsertOrUpdateWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputInsertWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputUpdateOrInsertWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputUpdateWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCRollbackWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCRowWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCSPWriter.java
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/JDBCConnectionTestIT.java
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/JDBCInputTestIT.java
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/JDBCOutputTestIT.java
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/JDBCRowTestIT.java
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/JDBCloseTestIT.java
Labels: Merged build passed

#1208 feat(TFD-2616): support Salesforce connector/dataset/input
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/dataprep/SalesforceInputDefinition.java
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/dataset/SalesforceDatasetDefinition.java
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/dataset/SalesforceDatasetProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/datastore/SalesforceDatastoreDefinition.java
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/dataset/messages.properties
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/dataset/messages_fr.properties
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/dataset/messages_ja.properties
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/dataset/SalesforceDatasetPropertiesTest.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/dataprep/SalesforceDataprepSource.java
  components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/runtime/dataprep/SalesforceDatasetRuntimeTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/runtime/dataprep/SalesforceInputTestIT.java
Labels: Merged build passed

#1214 Wwang talend/tup 5360
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/SalesforceModuleWizardDefinition.java
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/SalesforceConnectionProperties.properties
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/messages.properties
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/table.gif
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/SalesforceModuleWizardDefinitionTest.java
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/integration/SalesforceComponentTestIT.java
Labels: Merged build passed

#1190 fix(TDI-40138): add Custom lookup field for tMarketoInput/Output
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/tmarketoinput/TMarketoInputProperties.java
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/tmarketooutput/TMarketoOutputProperties.java
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/tmarketoinput/messages.properties
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/tmarketooutput/messages.properties
  components/components-marketo/components-marketo-definition/src/test/java/org/talend/components/marketo/tmarketoinput/TMarketoInputPropertiesTest.java
  components/components-marketo/components-marketo-definition/src/test/java/org/talend/components/marketo/tmarketooutput/TMarketoOutputPropertiesTest.java
  components/components-marketo/components-marketo-runtime/src/main/java/org/talend/components/marketo/runtime/client/MarketoLeadClient.java
Labels: Merged build passed, Need review

#1187 fix(TDI-40055): create a unique datastore path according applicationName
  components/components-googledrive/components-googledrive-definition/src/main/java/org/talend/components/google/drive/connection/GoogleDriveConnectionProperties.java
  components/components-googledrive/components-googledrive-definition/src/test/java/org/talend/components/google/drive/connection/GoogleDriveConnectionPropertiesTest.java
Labels: Merged build passed, Need review

#1172 chore(TDI-39894): upgrade Jackson version
  components-parent/pom.xml
  components/components-azurestorage/pom.xml
  components/components-bigquery/bigquery-integration/pom.xml
  components/components-bigquery/bigquery-runtime/pom.xml
  components/components-elasticsearch/elasticsearch-runtime_2_4/pom.xml
  components/components-fileio/simplefileio-runtime/pom.xml
  components/components-hadoopcluster/hadoopcluster-runtime/pom.xml
  components/components-hadoopcluster/hadoopcluster-runtime/src/main/java/org/apache/ambari/api/TextJacksonJsonProvider.java
  components/components-jira/pom.xml
  components/components-kafka/kafka-integration/pom.xml
  components/components-kinesis/kinesis-integration/pom.xml
  components/components-kinesis/kinesis-runtime/pom.xml
  components/components-netsuite/components-netsuite-runtime/pom.xml
  components/components-netsuite/components-netsuite-runtime_2016_2/pom.xml
  components/components-pubsub/pubsub-runtime/pom.xml
  components/components-salesforce/components-salesforce-runtime/pom.xml
  services/components-api-service-rest-all-components/pom.xml
  services/components-api-service-rest/pom.xml
Labels: Merged build passed, Need review, Work in progress(do not merge)

#1216 integrate JA trad for components 20180320
  components/components-fileio/simplefileio-definition/src/main/resources/org/talend/components/simplefileio/SimpleFileIODatasetProperties_ja.properties
  components/components-fileio/simplefileio-definition/src/main/resources/org/talend/components/simplefileio/s3/S3DatasetProperties_ja.properties
  components/components-kafka/kafka-definition/src/main/resources/org/talend/components/kafka/dataset/KafkaDatasetProperties_ja.properties
  components/components-kafka/kafka-definition/src/main/resources/org/talend/components/kafka/datastore/KafkaDatastoreProperties_ja.properties
  components/components-kinesis/kinesis-definition/src/main/resources/org/talend/components/kinesis/KinesisDatasetProperties_ja.properties
  components/components-localio/localio-definition/src/main/resources/org/talend/components/localio/fixed/FixedDatasetDefinition_ja.properties
  components/components-localio/localio-definition/src/main/resources/org/talend/components/localio/fixed/FixedDatastoreDefinition_ja.properties
  components/components-localio/localio-definition/src/main/resources/org/talend/components/localio/fixed/FixedInputDefinition_ja.properties
  components/components-marklogic/components-marklogic-definition/src/main/resources/org/talend/components/marklogic/tmarklogicbulkload/MarkLogicBulkLoadProperties_ja.properties
  components/components-processing/processing-definition/src/main/resources/org/talend/components/processing/definition/aggregate/AggregateGroupByProperties_ja.properties
  components/components-processing/processing-definition/src/main/resources/org/talend/components/processing/definition/aggregate/AggregateOperationProperties_ja.properties
  components/components-processing/processing-definition/src/main/resources/org/talend/components/processing/definition/aggregate/AggregateProperties_ja.properties
  components/components-processing/processing-definition/src/main/resources/org/talend/components/processing/definition/fieldselector/FieldSelectorDefinition_ja.properties
  components/components-processing/processing-definition/src/main/resources/org/talend/components/processing/definition/fieldselector/messages_ja.properties
  components/components-processing/processing-definition/src/main/resources/org/talend/components/processing/definition/limit/LimitDefinition_ja.properties
  components/components-processing/processing-definition/src/main/resources/org/talend/components/processing/definition/limit/messages_ja.properties
  components/components-processing/processing-definition/src/main/resources/org/talend/components/processing/definition/typeconverter/messages_ja.properties
  components/components-processing/processing-definition/src/main/resources/org/talend/components/processing/definition/window/messages_ja.properties
Labels: Merged build passed

#1219 Ypiel/tdi 40149 salesforce long running query patch
  components/components-salesforce/components-salesforce-definition/pom.xml
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/SalesforceConnectionProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforceinput/TSalesforceInputProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/SalesforceConnectionProperties.properties
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/tsalesforceinput/messages.properties
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforceinput/TSalesforceInputPropertiesTest.java
  components/components-salesforce/components-salesforce-integration/pom.xml
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/integration/SalesforceComponentTestIT.java
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSinkTestIT.java
  components/components-salesforce/components-salesforce-runtime/pom.xml
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/connection/oauth/SalesforceOAuthConnection.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/BulkResultAdapterFactory.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkQueryInputReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.java
Labels: Merged build failed, Reviewing

#1225 fix(TDI-40274): restore AzureStorage components trigger OnSubjobX
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/AzureStorageDefinition.java
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/queue/tazurestoragequeueinput/TAzureStorageQueueInputDefinition.java
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/queue/tazurestoragequeueinputloop/TAzureStorageQueueInputLoopDefinition.java
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/table/tazurestorageinputtable/TAzureStorageInputTableDefinition.java
  components/components-azurestorage/src/test/java/org/talend/components/azurestorage/AzureStorageComponentsTest.java
Labels: Merged build passed, Need review

#1222 fix(TDI-40138): add migration for the custom lookups
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/MarketoComponentProperties.java
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/tmarketoinput/TMarketoInputProperties.java
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/tmarketooutput/TMarketoOutputProperties.java
Labels: Need review

#1215 feat(TFD-3909): support condition in salesforce input for module type
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/dataprep/SalesforceInputProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/dataset/SalesforceDatasetProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/dataset/messages.properties
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/dataset/messages_fr.properties
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/dataset/messages_ja.properties
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/dataprep/SalesforceInputPropertiesTest.java
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/dataset/SalesforceDatasetPropertiesTest.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/dataprep/SalesforceBulkQueryReader.java
  components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/runtime/dataprep/SalesforceDatasetRuntimeTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/runtime/dataprep/SalesforceInputTestIT.java
Labels: Merged build passed

#1221 Mbasiuk/tdi 40257 add safety switch property
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforceinput/TSalesforceInputProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/tsalesforceinput/messages.properties
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/migration/SalesforceInputPropertiesMigrationTaskTest.java
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforceinput/TSalesforceInputPropertiesTest.java
  components/components-salesforce/components-salesforce-definition/src/test/resources/org/talend/components/salesforce/migration/tSalesforceInputProperties_701.json
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkQueryInputReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
  components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/BulkResultSetTest.java
Labels: Merged build passed, Need review

#1228 chore(TDI-40287): upgrade snowflake driver to 3.5.3 version
  components/components-snowflake/pom.xml
Labels: Merged build passed, Need review

#1230 fix(TDI-40149) : Ne need to refresh form
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforceinput/TSalesforceInputProperties.java
Labels: Merged build failed

#1226 fix(TDI-40275): fix GoogleDriveConnection DatastorePath behavior
  components/components-googledrive/components-googledrive-definition/src/main/java/org/talend/components/google/drive/connection/GoogleDriveConnectionProperties.java
  components/components-googledrive/components-googledrive-definition/src/test/java/org/talend/components/google/drive/connection/GoogleDriveConnectionPropertiesTest.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveRuntime.java
Labels: Merged build passed

#1231 fix(TDI-40222): close sandboxInstance correctly
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/MarketoComponentDefinition.java
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/tmarketoconnection/TMarketoConnectionProperties.java
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/tmarketoinput/TMarketoInputProperties.java
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/wizard/MarketoCustomObjectsSchemasProperties.java
Labels: Need review

#1227 fix(TFD-3920) : use supplied avro schema in kafka dataset
  components/components-kafka/kafka-runtime/src/main/java/org/talend/components/kafka/runtime/KafkaOutputPTransformRuntime.java
Labels: Merged build passed

#1220 (TDI-40129) Upgrade to CXF 3.2.3
  components/components-netsuite/components-netsuite-runtime/pom.xml
  components/components-netsuite/components-netsuite-runtime_2014_2/pom.xml
  components/components-netsuite/components-netsuite-runtime_2016_2/pom.xml
Labels: Merged build passed, Need review

#1235 fix(TDI-40275): GoogleDrive swt libs
  components/components-googledrive/components-googledrive-definition/src/main/java/org/talend/components/google/drive/connection/GoogleDriveConnectionProperties.java
  components/components-googledrive/components-googledrive-definition/src/test/java/org/talend/components/google/drive/connection/GoogleDriveConnectionPropertiesTest.java
  components/components-googledrive/components-googledrive-runtime/pom.xml
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveRuntime.java
Labels: Merged build passed

#1233 Mbasiuk/tdi 40012 fix db columns
  components/components-snowflake/src/main/java/org/talend/components/snowflake/SnowflakeConnectionProperties.java
  components/components-snowflake/src/main/java/org/talend/components/snowflake/runtime/SnowflakeAvroRegistry.java
  components/components-snowflake/src/main/java/org/talend/components/snowflake/runtime/SnowflakeReader.java
  components/components-snowflake/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
  components/components-snowflake/src/test/java/org/talend/components/snowflake/runtime/SnowflakeAvroRegistryTest.java
  components/components-snowflake/src/test/java/org/talend/components/snowflake/runtime/SnowflakeReaderTest.java
  components/components-snowflake/src/test/java/org/talend/components/snowflake/runtime/SnowflakeWriterTest.java
  components/components-snowflake/src/test/java/org/talend/components/snowflake/test/SnowflakeRuntimeIT.java
Labels: Merged build passed

#1236 fix(TUP-19789): NPE error occurred in error log when check "Test connect" button with no any input connection parameters
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JdbcRuntimeUtils.java
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/JDBCConnectionTestIT.java
Labels: Merged build passed
