Repository Talend/components, pull requests merged in 2019-06, with the labels that each got.

#1486 fix(TDI-42396): Upgrade jackson dependency
  components-parent/components-bom/pom.xml
  services/components-api-service-rest-all-components/pom.xml
  services/components-api-service-rest/pom.xml
Labels: Merged build passed, Need review

#1488 feat(TDI-41141):Update SalesForce API to 45.0
  components-parent/components-bom/pom.xml
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/SalesforceConnectionProperties.java
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/integration/SalesforceComponentTestIT.java
  components/components-salesforce/components-salesforce-runtime/pom.xml
Labels: Merged build passed, Need review

#1487 feat(TDI-41721) : support athenadb in jdbc component
  services/components-maven-repo/config/jdbc_config.json
  services/components-maven-repo/pom.xml
Labels: Merged build passed

#1489 fix(TDI-42358): Support materialized views
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeSourceOrSink.java
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/SnowflakeSourceOrSinkTest.java
Labels: Merged build passed

#1485 feat(TDI-42393): Rename couchbase components
  components/components-couchbase/src/main/java/org/talend/components/couchbase/input/CouchbaseInputDefinition.java
  components/components-couchbase/src/main/java/org/talend/components/couchbase/output/CouchbaseOutputDefinition.java
  components/components-couchbase/src/main/resources/org/talend/components/couchbase/input/messages.properties
  components/components-couchbase/src/main/resources/org/talend/components/couchbase/input/tCouchbaseDCPInput_icon32.png
  components/components-couchbase/src/main/resources/org/talend/components/couchbase/input/tCouchbaseDCPInput_icon32.xcf
  components/components-couchbase/src/main/resources/org/talend/components/couchbase/output/messages.properties
  components/components-couchbase/src/main/resources/org/talend/components/couchbase/output/tCouchbaseDCPOutput_icon32.png
  components/components-couchbase/src/main/resources/org/talend/components/couchbase/output/tCouchbaseDCPOutput_icon32.xcf
Labels: Merged build failed, Need review

#1493 Igonchar/tdi 42396 fix jackson version
  components-parent/components-bom/pom.xml
Labels: Merged build failed
