Repository Talend/components, pull requests merged in 2019-11, with the labels that each got.

#1506 fix(TDI-42556): remove redundant dependencies from Netsuite definition
  components/components-netsuite/components-netsuite-definition/pom.xml
  components/components-netsuite/components-netsuite-definition/src/test/java/org/talend/components/netsuite/OsgiNetSuiteComponentTestIT.java
  components/components-netsuite/components-netsuite-runtime/pom.xml
Labels: Merged build passed

#1543 feat(TDI-41954): Snowflake Commit and Rollback
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeConnectionProperties.java
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeDefinition.java
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeFamilyDefinition.java
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeRollbackAndCommitProperties.java
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/tsnowflakecommit/TSnowflakeCommitDefinition.java
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/tsnowflakerollback/TSnowflakeRollbackDefinition.java
  components/components-snowflake/components-snowflake-definition/src/main/resources/org/talend/components/snowflake/SnowflakeConnectionProperties.properties
  components/components-snowflake/components-snowflake-definition/src/main/resources/org/talend/components/snowflake/SnowflakeRollbackAndCommitProperties.properties
  components/components-snowflake/components-snowflake-definition/src/main/resources/org/talend/components/snowflake/tsnowflakecommit/messages.properties
  components/components-snowflake/components-snowflake-definition/src/main/resources/org/talend/components/snowflake/tsnowflakecommit/tSnowflakeCommit_icon32.png
  components/components-snowflake/components-snowflake-definition/src/main/resources/org/talend/components/snowflake/tsnowflakerollback/messages.properties
  components/components-snowflake/components-snowflake-definition/src/main/resources/org/talend/components/snowflake/tsnowflakerollback/tSnowflakeRollback_icon32.png
  components/components-snowflake/components-snowflake-definition/src/test/java/org/talend/components/snowflake/SnowflakeRollbackAndCommitPropertiesTest.java
  components/components-snowflake/components-snowflake-definition/src/test/java/org/talend/components/snowflake/tsnowflakecommit/TSnowflakeCommitDefinitionTest.java
  components/components-snowflake/components-snowflake-definition/src/test/java/org/talend/components/snowflake/tsnowflakerollback/TSnowflakeRollbackDefinitionTest.java
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeCommitAndRollbackTestIT.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeCommitSourceOrSink.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeRollbackSourceOrSink.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeRuntime.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeStandaloneOperation.java
  components/components-snowflake/components-snowflake-runtime/src/main/resources/org/talend/components/snowflake/runtime/SnowflakeStandaloneOperation.properties
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/SnowflakeStandaloneOperationTest.java
Labels: Merged build passed, Need review

#1544 Fix(TDI-34953):Enable tJDBCOutput print sql.
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcoutput/messages.properties
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/type/DebugUtil.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/type/RowWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputDeleteWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputInsertOrUpdateWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputInsertWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputUpdateOrInsertWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputUpdateWriter.java
Labels: Merged build failed

#1539 feat(TDI-42911) Migration after Remove CryptoHelper to use AES
  components-parent/components-bom/pom.xml
  components-parent/pom.xml
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/s3/S3DatastoreProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/datastore/JDBCDatastoreProperties.java
  components/components-kinesis/kinesis-definition/src/main/java/org/talend/components/kinesis/KinesisDatastoreProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/datastore/SalesforceDatastoreProperties.java
  core/components-api/pom.xml
  core/components-api/src/main/java/org/talend/components/api/properties/ComponentBasePropertiesImpl.java
  core/components-api/src/main/java/org/talend/components/api/properties/ComponentEncryption.java
  core/components-api/src/main/java/org/talend/components/api/properties/ComponentKeySource.java
  core/components-api/src/main/java/org/talend/components/api/properties/ComponentPropertiesImpl.java
  core/components-api/src/main/resources/org/talend/components/api/properties/component.keys
  core/components-api/src/test/java/org/talend/components/api/properties/ComponentEncryptionTest.java
  core/components-api/src/test/java/org/talend/components/api/properties/ComponentKeySourceTest.java
  core/components-common/src/main/java/org/talend/components/common/UserPasswordProperties.java
  core/components-osgi-test/components-osgitest/pom.xml
  core/components-osgi-test/components-osgitest/src/main/java/org/talend/components/api/ComponentsPaxExamOptions.java
  services/components-api-service-rest-all-components/pom.xml
  services/components-api-service-rest/pom.xml
Labels: Merged build passed

#1550 fix(TDI-43092): remove reginID snowflake
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeConnectionProperties.java
  components/components-snowflake/components-snowflake-definition/src/test/java/org/talend/components/snowflake/SnowflakeConnectionPropertiesTest.java
Labels: Merged build passed

#1552 chore(TDI-43269): set default value to true, fix test
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeRollbackAndCommitProperties.java
  components/components-snowflake/components-snowflake-definition/src/test/java/org/talend/components/snowflake/SnowflakeRollbackAndCommitPropertiesTest.java
Labels: Need review

#1547 feat(TDI-43088): Update cxf dep for tcompv0
  components-parent/components-bom/pom.xml
  components-parent/pom.xml
Labels: Merged build failed

#1553 TDI-43286 - Update pax-url in the components repo
  components-parent/components-bom/pom.xml
  core/components-osgi-test/components-osgitest/pom.xml
  services/components-api-service-rest/pom.xml
Labels: Merged build passed
