Repository Talend/components, pull requests merged in 2019-09, with the labels that each got.

#1527 fix(TUP-24385) Cannot connect hadoop cluster
  components/components-hadoopcluster/hadoopcluster-runtime/src/main/java/org/talend/components/hadoopcluster/runtime/configuration/HadoopCMConfigurator.java
Labels: Merged build passed

#1529 fix(TDI-42686): fix "doing operations on a closed result set"
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeRowStandalone.java
Labels: Merged build failed

#1528 fix(TDI-42892):remove endpoint restraint azure
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/AzureConnectionWithSasService.java
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/blob/runtime/AzureStorageRuntime.java
  components/components-azurestorage/src/test/java/org/talend/components/azurestorage/blob/runtime/AzureStorageRuntimeTest.java
Labels: Merged build passed

#1530 fix(TDI-42892):Eliminate restraint of Azure SAS
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/blob/runtime/AzureStorageRuntime.java
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/utils/SharedAccessSignatureUtils.java
  components/components-azurestorage/src/test/java/org/talend/components/azurestorage/utils/SharedAccessSignatureUtilsTest.java
Labels: Merged build passed

#1532 fix(TDI-42953): Two tujs failed related JDBCInput component for 731
  components/components-jdbc/components-jdbc-integration/src/test/java/org/talend/components/jdbc/dataprep/JdbcInputTestIT.java
  components/components-jdbc/components-jdbc-integration/src/test/java/org/talend/components/jdbc/integration/JdbcRowTestIT.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCInputReader.java
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/JDBCInputTestIT.java
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/JDBCRowTestIT.java
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/common/DBTestUtils.java
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/dataprep/JDBCInputTestIT.java
Labels: Merged build passed

#1522 fix(TDI-42834): update commons-compress library version to latest
  components-parent/components-bom/pom.xml
Labels: Merged build failed, Need review
