Repository Talend/components, pull requests merged in 2019-12, with the labels that each got.

#1555 fix(TDI-43085): Update jackson deps to the 2.10.1
  components-parent/components-bom/pom.xml
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/json/NsTypeResolverBuilder.java
  services/components-api-service-rest-all-components/pom.xml
  services/components-api-service-rest/pom.xml
Labels: Merged build failed

#1557 fix(TDI-43348): hide autocommit property
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeConnectionTableProperties.java
Labels: Merged build passed

#1558 fix(TDI-43085): Fix hadoop compile error
  components/components-hadoopcluster/hadoopcluster-runtime/src/main/java/org/apache/ambari/api/TextJacksonJsonProvider.java
Labels: Merged build passed

#1554 fix(TDI-42556): remove redundant dependencies from Netsuite definitio…
  components-parent/components-bom/pom.xml
  components/components-netsuite/components-netsuite-definition/pom.xml
  components/components-netsuite/components-netsuite-definition/src/test/java/org/talend/components/netsuite/OsgiNetSuiteComponentTestIT.java
  components/components-netsuite/components-netsuite-runtime/pom.xml
Labels: Merged build passed

#1560 fix(TDI-43085): Fix failing test for snowflake
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeWritersTestIT.java
Labels: Merged build passed

#1556 fix(TDI-43233):Salesforce subquery with multiple records and record field include null field value would missing
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceInputReaderTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SObjectAdapterFactory.java
Labels: Merged build passed, Need review

#1559 feat(TDI-41953): snowflake key pair auth
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeConnectionProperties.java
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/tsnowflakeconnection/AuthenticationType.java
  components/components-snowflake/components-snowflake-definition/src/main/resources/org/talend/components/snowflake/SnowflakeConnectionProperties.properties
  components/components-snowflake/components-snowflake-definition/src/test/java/org/talend/components/snowflake/SnowflakeConnectionPropertiesTest.java
  components/components-snowflake/components-snowflake-integration/pom.xml
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeConnectionKeyPairIT.java
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeTestIT.java
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeWritersTestIT.java
Labels: Merged build failed, Need review

#1563 fix(TDI-43392): upgrade libraries to 3.2.1 version
  components-parent/components-bom/pom.xml
  components/components-fileio/simplefileio-runtime/pom.xml
  core/components-adapter-beam-parent/pom.xml
Labels: Merged build passed
