Repository Talend/components, pull requests merged in 2019-08, with the labels that each got.

#1510 feat(TDI-41692):Salesforce: Dynamic Upsert for Bulkload with monitoring through component Variable
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforcebulkexec/TSalesforceBulkExecProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/tsalesforcebulkexec/messages.properties
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforcebulkexec/TSalesforceBulkExecPropertiesTest.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/BulkResult.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/BulkResultAdapterFactory.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkExecReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
  components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/BulkResultAdapterFactoryTest.java
Labels: Merged build failed, Need review

#1509 fix(TDI-36014):tjdbcInput prepare statement
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcinput/TJDBCInputProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcinput/messages.properties
  components/components-jdbc/components-jdbc-definition/src/test/java/org/talend/components/jdbc/tjdbcinput/TJDBCInputPropertiesTest.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCInputReader.java
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/JDBCInputTestIT.java
Labels: Merged build passed

#1511 fix(TDI-42747): tJDBCOutput does not work with BLOB dataType
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/schemainfer/SchemaInferer.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/type/JDBCMapping.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/type/RowWriter.java
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/JDBCInputTestIT.java
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/common/DBTestUtils.java
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/type/JDBCTypeMappingTestIT.java
  core/components-common/src/main/java/org/talend/components/common/avro/JDBCAvroRegistry.java
Labels: Merged build passed

#1516 fix(TDI-42747): fix the runtime confilct with the pre commit
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/JDBCInputTestIT.java
Labels: Merged build failed

#1513 Bhe/bugfix/tup 22575 upgrade org eclipse jdt core
  components/components-hadoopcluster/hadoopcluster-runtime/pom.xml
  components/components-hadoopcluster/hadoopcluster-runtime/src/main/java/org/talend/components/hadoopcluster/runtime/configuration/HadoopCMCluster.java
  components/components-hadoopcluster/hadoopcluster-runtime/src/main/java/org/talend/components/hadoopcluster/runtime/configuration/HadoopCMClusterService.java
  components/components-hadoopcluster/hadoopcluster-runtime/src/main/java/org/talend/components/hadoopcluster/runtime/configuration/HadoopCMConfigurator.java
  components/components-hadoopcluster/hadoopcluster-runtime/src/main/java/org/talend/components/hadoopcluster/runtime/configuration/HadoopConfigurator.java
Labels: Merged build passed

#1515 fix(TDI-42709): add Array supports [Backport to 7.1]
  components/components-couchbase/src/main/java/org/talend/components/couchbase/runtime/CouchbaseWriter.java
  components/components-couchbase/src/test/java/org/talend/components/couchbase/runtime/CouchbaseWriterTest.java
Labels: Merged build passed, Need review

#1514 fix(TDI-42709): add Array supports [Backport to 7.2]
  components/components-couchbase/src/main/java/org/talend/components/couchbase/runtime/CouchbaseWriter.java
  components/components-couchbase/src/test/java/org/talend/components/couchbase/runtime/CouchbaseWriterTest.java
Labels: Merged build passed, Need review

#1498 fix(TDI-42178): Snowflake timezone issues
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/Formatter.java
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/FormatterTest.java
Labels: Merged build passed

#1520 fix(TDI-42866): downgrade temporarily daikon version to 0.31.8
  components-parent/components-bom/pom.xml
  components-parent/pom.xml
  services/components-api-service-rest-all-components/pom.xml
  services/components-api-service-rest/pom.xml
Labels: Merged build passed

#1519 bug(TDI-42686): [7.1.1] snowflake JDBC driver in tcompv0
  components-parent/components-bom/pom.xml
  services/components-maven-repo/config/jdbc_config.json
  services/components-maven-repo/pom.xml
Labels: Merged build passed

#1505 fix(TDI-42653): reduce REST API calls
  components/components-marketo/components-marketo-runtime/src/main/java/org/talend/components/marketo/runtime/MarketoAccessTokenPool.java
  components/components-marketo/components-marketo-runtime/src/main/java/org/talend/components/marketo/runtime/MarketoSourceOrSink.java
  components/components-marketo/components-marketo-runtime/src/main/java/org/talend/components/marketo/runtime/client/MarketoBaseRESTClient.java
  components/components-marketo/components-marketo-runtime/src/main/java/org/talend/components/marketo/runtime/client/MarketoRESTClient.java
Labels: Merged build passed, Need review

#1525 fix(TUP-24330) Cannot retrieve conf from cdh512
  components/components-hadoopcluster/hadoopcluster-runtime/src/main/java/org/talend/components/hadoopcluster/runtime/configuration/HadoopCMConfigurator.java
Labels: Merged build passed

#1521 Igonchar/tdi 42854 snowflake dynamic
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeRuntimeIT.java
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeWritersTestIT.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
Labels: Merged build passed
