Repository Talend/components, pull requests merged in 2019-05, with the labels that each got.

#1479 fix(TDI-42154): Escape char in Couchbase data
  components/components-couchbase/src/main/java/org/talend/components/couchbase/output/CouchbaseOutputProperties.java
  components/components-couchbase/src/main/java/org/talend/components/couchbase/runtime/CouchbaseConnection.java
  components/components-couchbase/src/main/java/org/talend/components/couchbase/runtime/CouchbaseSink.java
  components/components-couchbase/src/main/java/org/talend/components/couchbase/runtime/CouchbaseWriter.java
  components/components-couchbase/src/main/resources/org/talend/components/couchbase/output/messages.properties
  components/components-couchbase/src/test/java/org/talend/components/couchbase/runtime/CouchbaseWriterTest.java
Labels: Merged build passed, Need review

#1481 fix(TDI-42307): Duplicate field errorCode in record rejectOutput
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/CommonUtils.java
  components/components-jdbc/components-jdbc-definition/src/test/java/org/talend/components/jdbc/CommonUtilsTest.java
Labels: Merged build passed

#1477 fix(TDI-42281): add missing customLookupField to tMarketoBulkExec
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/tmarketobulkexec/TMarketoBulkExecProperties.java
  components/components-marketo/components-marketo-definition/src/main/resources/org/talend/components/marketo/tmarketobulkexec/messages.properties
  components/components-marketo/components-marketo-runtime/src/main/java/org/talend/components/marketo/runtime/client/MarketoBulkExecClient.java
Labels: Merged build passed

#1483 kjwang/Fix TUP-21205 Remove CryptoHelper (Update daikon version)
  components-parent/components-bom/pom.xml
  components-parent/pom.xml
  services/components-api-service-rest-all-components/pom.xml
  services/components-api-service-rest/pom.xml
Labels: Merged build failed

#1484 fix(TDI-42154): Escape char in Couchbase data (backport)
  components/components-couchbase/src/main/java/org/talend/components/couchbase/output/CouchbaseOutputProperties.java
  components/components-couchbase/src/main/java/org/talend/components/couchbase/runtime/CouchbaseConnection.java
  components/components-couchbase/src/main/java/org/talend/components/couchbase/runtime/CouchbaseSink.java
  components/components-couchbase/src/main/java/org/talend/components/couchbase/runtime/CouchbaseWriter.java
  components/components-couchbase/src/main/resources/org/talend/components/couchbase/output/messages.properties
  components/components-couchbase/src/test/java/org/talend/components/couchbase/runtime/CouchbaseWriterTest.java
Labels: Merged build passed, Need review
