Repository Talend/components, pull requests merged in 2019-07, with the labels that each got.

#1500 fix(TDI-42543): REST syncLead behavior
  components/components-marketo/components-marketo-integration/src/test/java/org/talend/components/marketo/runtime/client/MarketoRESTClientTestIT.java
  components/components-marketo/components-marketo-runtime/src/main/java/org/talend/components/marketo/runtime/MarketoOutputWriter.java
Labels: Merged build passed

#1499 feat(TDI-32103):add support hardDelete on salesforce
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/SalesforceOutputProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforcebulkexec/TSalesforceBulkExecProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/messages.properties
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforcebulkexec/TSalesforceBulkExecPropertiesTest.java
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputPropertiesTest.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkExecReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkExecRuntime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
Labels: Merged build passed

#1502 chore: update Daikon version to 0.31.9-SNAPSHOT
  components-parent/components-bom/pom.xml
  components-parent/pom.xml
  services/components-api-service-rest-all-components/pom.xml
  services/components-api-service-rest/pom.xml
Labels: Merged build passed

#1501 fix(TDI-42548): migrate batchSize to 1 for the sync* operations
  components/components-marketo/components-marketo-definition/src/main/java/org/talend/components/marketo/tmarketooutput/TMarketoOutputProperties.java
  components/components-marketo/components-marketo-definition/src/test/java/org/talend/components/marketo/tmarketooutput/TMarketoOutputPropertiesTest.java
Labels: Merged build passed

#1508 fix(TDI-42608): Salesforce bulk query batch job can't be closed when …
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkQueryInputReader.java
Labels: Merged build failed

#1507 fix(TDI-42709): add Array supports
  components/components-couchbase/src/main/java/org/talend/components/couchbase/runtime/CouchbaseWriter.java
  components/components-couchbase/src/test/java/org/talend/components/couchbase/runtime/CouchbaseWriterTest.java
Labels: Merged build passed, Need review
