Repository Talend/components, pull requests merged in 2020-02, with the labels that each got.

#1575 fix(TDI-43515): Support MariaDB 10.X. Update mariadb-java-client to 2…
  services/components-maven-repo/config/jdbc_config.json
  services/components-maven-repo/pom.xml
Labels: Merged build failed

#1573 feat(TDI-43487): Update snowflake jdbc driver
  components-parent/components-bom/pom.xml
  services/components-maven-repo/config/jdbc_config.json
  services/components-maven-repo/pom.xml
Labels: Merged build failed, Need review

#1585 Igonchar/tdi 43590 fix pom bugs 2
  components-parent/components-bom/pom.xml
  components-parent/components-p2update-assembly/pom.xml
  components-parent/pom.xml
  components/components-bigquery/bigquery-integration/pom.xml
  components/components-bigquery/bigquery-runtime/pom.xml
  components/components-elasticsearch/elasticsearch-integration/pom.xml
  components/components-elasticsearch/elasticsearch-runtime_2_4/pom.xml
  components/components-fileio/fileio-integration/pom.xml
  components/components-fileio/s3-runtime-di/pom.xml
  components/components-fileio/simplefileio-definition/pom.xml
  components/components-fileio/simplefileio-runtime/pom.xml
  components/components-googledrive/components-googledrive-integration/pom.xml
  components/components-googledrive/components-googledrive-runtime/pom.xml
  components/components-hadoopcluster/hadoopcluster-runtime/pom.xml
  components/components-jdbc/components-jdbc-integration/pom.xml
  components/components-jdbc/components-jdbc-runtime-beam/pom.xml
  components/components-jdbc/components-jdbc-runtime/pom.xml
  components/components-kafka/kafka-integration/pom.xml
  components/components-kafka/kafka-runtime/pom.xml
  components/components-kinesis/kinesis-integration/pom.xml
  components/components-kinesis/kinesis-runtime/pom.xml
  components/components-localio/localio-integration/pom.xml
  components/components-localio/localio-runtime/pom.xml
  components/components-marketo/components-marketo-integration/pom.xml
  components/components-marketo/components-marketo-runtime/pom.xml
  components/components-marklogic/components-marklogic-definition/pom.xml
  components/components-marklogic/components-marklogic-runtime/pom.xml
  components/components-netsuite/components-netsuite-runtime/pom.xml
  components/components-netsuite/components-netsuite-runtime_2014_2/pom.xml
  components/components-netsuite/components-netsuite-runtime_2016_2/pom.xml
  components/components-netsuite/components-netsuite-runtime_2018_2/pom.xml
  components/components-processing/processing-runtime/pom.xml
  components/components-pubsub/pubsub-integration/pom.xml
  components/components-pubsub/pubsub-runtime/pom.xml
  components/components-salesforce/components-salesforce-integration/pom.xml
  components/components-salesforce/components-salesforce-runtime/pom.xml
  components/components-snowflake/components-snowflake-integration/pom.xml
  components/components-snowflake/components-snowflake-runtime/pom.xml
  core/components-osgi-test/components-osgitest/pom.xml
  core/components-osgi-test/osgi-test-component/pom.xml
  examples/components-api-archetypes/bd-component-archetype/src/main/resources/archetype-resources/__componentNameLowerCase__-runtime/pom.xml
  examples/components-api-archetypes/input-component-archetype/src/main/resources/archetype-resources/__rootArtifactId__-runtime/pom.xml
  examples/components-api-archetypes/processing-bd-component-archetype/src/main/resources/archetype-resources/processing-runtime/src/main/java/runtime/__componentNameLowerCase__/pom.xml
  examples/components-multiple-runtimes-and-deps/multiple-runtime-comp/pom.xml
  examples/components-multiple-runtimes-and-deps/test-multiple-runtime-comp-runtime_v01/pom.xml
  examples/components-multiple-runtimes-and-deps/test-multiple-runtime-comp-runtime_v02/pom.xml
  examples/components-multiple-runtimes-and-deps/test-multiple-runtime-comp/pom.xml
  pom.xml
  services/components-api-service-rest-all-components/pom.xml
  services/components-api-service-rest/pom.xml
  services/components-api-service-spi-test/pom.xml
  services/components-maven-repo/pom.xml
Labels: Merged build passed

#1587 Igonchar/tdi 43587 fix maven central
  components-parent/components-bom/pom.xml
  components-parent/pom.xml
  services/components-api-service-rest-all-components/assembly/no-arch.xml
  services/components-api-service-rest-all-components/pom.xml
  services/components-api-service-rest/pom.xml
  services/components-api-service-rest/scripts/start.bat
  services/components-api-service-rest/scripts/start.sh
  services/components-api-service-rest/src/main/resources/org/talend/daikon/sandbox/properties/sun.conf
Labels: Merged build failed

#1581 Clesaec/tdi 41193 fileio outofmemory 027
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/SimpleFileIODatasetProperties.java
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/s3/S3DatasetProperties.java
  components/components-fileio/simplefileio-definition/src/main/resources/org/talend/components/simplefileio/SimpleFileIODatasetProperties.properties
  components/components-fileio/simplefileio-definition/src/main/resources/org/talend/components/simplefileio/s3/S3DatasetProperties.properties
  components/components-fileio/simplefileio-definition/src/test/java/org/talend/components/simplefileio/SimpleFileIODatasetPropertiesTest.java
  components/components-fileio/simplefileio-definition/src/test/java/org/talend/components/simplefileio/s3/S3DatasetPropertiesTest.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/SimpleFileIOInputRuntime.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/SimpleFileIOOutputRuntime.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/SimpleRecordFormatCsvIO.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/beamcopy/ConfigurableHDFSFileSource.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/beamcopy/FileParameterException.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/beamcopy/LimitedLineRecordReader.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/s3/S3InputRuntime.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/s3/S3OutputRuntime.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/sources/CsvHdfsFileSource.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/SimpleFileIODatasetRuntimeTest.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/test/RecordSetUtil.java
Labels: Merged build passed

#1591 fix(TDI-41193) : limit csv to
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/SimpleFileIODatasetProperties.java
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/s3/S3DatasetProperties.java
  components/components-fileio/simplefileio-definition/src/main/resources/org/talend/components/simplefileio/SimpleFileIODatasetProperties.properties
  components/components-fileio/simplefileio-definition/src/main/resources/org/talend/components/simplefileio/s3/S3DatasetProperties.properties
  components/components-fileio/simplefileio-definition/src/test/java/org/talend/components/simplefileio/SimpleFileIODatasetPropertiesTest.java
  components/components-fileio/simplefileio-definition/src/test/java/org/talend/components/simplefileio/s3/S3DatasetPropertiesTest.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/SimpleFileIOInputRuntime.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/SimpleFileIOOutputRuntime.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/SimpleRecordFormatCsvIO.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/beamcopy/ConfigurableHDFSFileSource.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/beamcopy/FileParameterException.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/beamcopy/LimitedLineRecordReader.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/hadoop/csv/CSVFileRecordReader.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/s3/S3InputRuntime.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/s3/S3OutputRuntime.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/sources/CsvHdfsFileSource.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/SimpleFileIODatasetRuntimeTest.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/test/RecordSetUtil.java
Labels: Merged build passed

#1583 fix(TDI-43605): Unify referenced connection key for tcomp components
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/NetSuiteEndpoint.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeRuntime.java
Labels: Merged build passed

#1590 fix(TDI-43587): fix maven central url in application.properties
  services/components-api-service-rest/src/main/resources/application.properties
Labels: Merged build passed

#1586 Mbasiuk/tdi 42938 default date mapping
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/tsnowflakeoutput/DateMapping.java
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/tsnowflakeoutput/TSnowflakeOutputProperties.java
  components/components-snowflake/components-snowflake-definition/src/main/resources/org/talend/components/snowflake/tsnowflakeoutput/messages.properties
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/tableaction/SnowflakeTableActionConfig.java
Labels: Merged build passed, Need review

#1595 fix(TDI-43437): Support Snowflake SSO authenticate through SiteMinder
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/module/JDBCTableSelectionModule.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcinput/TJDBCInputProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcoutput/TJDBCOutputProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/wizard/JDBCConnectionWizardProperties.java
  components/components-jdbc/components-jdbc-integration/src/test/java/org/talend/components/jdbc/integration/JdbcRowTestIT.java
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/JDBCConnectionTestIT.java
Labels: Merged build failed

#1594 Igonchar/tdi 43587 add missing s3 deps
  components-parent/components-bom/pom.xml
  components/components-fileio/simplefileio-runtime/pom.xml
  services/components-api-service-rest-all-components/pom.xml
  services/components-api-service-rest/pom.xml
  services/components-api-service-rest/scripts/start.bat
  services/components-api-service-rest/scripts/start.sh
  services/components-maven-repo/pom.xml
Labels: Merged build passed

#1598 Revert "fix(TDI-43605): Unify referenced connection key for tcomp com…
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/NetSuiteEndpoint.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeRuntime.java
Labels: Merged build passed

#1599 Revert "fix(TDI-43092): remove reginID snowflake (#1550)"
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeConnectionProperties.java
  components/components-snowflake/components-snowflake-definition/src/test/java/org/talend/components/snowflake/SnowflakeConnectionPropertiesTest.java
Labels: Merged build passed

#1603 fix(tdi-43629): handle autoincremented default values
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeWritersTestIT.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeAvroRegistry.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
  core/components-common/src/main/java/org/talend/components/common/avro/JDBCAvroRegistry.java
Labels: Merged build failed, Need review

#1602 fix(TDI-43605): Unify referenced connection key for tcomp components …
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/NetSuiteEndpoint.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeRuntime.java
Labels: Merged build passed, Need review

#1609 fix(TDI-43682): fix custom transaction types
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/SchemaCustomMetaDataSource.java
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/CustomMetaDataSource.java
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/DefaultCustomMetaDataSource.java
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/DefaultMetaDataSource.java
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/EmptyCustomMetaDataSource.java
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/BasicRecordType.java
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/CustomTransactionTypeInfo.java
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/RefType.java
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/search/SearchQuery.java
  components/components-netsuite/components-netsuite-runtime/src/test/java/org/talend/components/netsuite/AbstractNetSuiteTestBase.java
  components/components-netsuite/components-netsuite-runtime/src/test/java/org/talend/components/netsuite/client/CustomMetaDataSourceTest.java
  components/components-netsuite/components-netsuite-runtime/src/test/java/org/talend/components/netsuite/client/SearchQueryTest.java
  components/components-netsuite/components-netsuite-runtime/src/test/java/org/talend/components/netsuite/client/model/BasicMetaDataTest.java
Labels: Merged build passed, Need review
