Repository Talend/components, pull requests merged in 2020-08, with the labels that each got.

#1702 fix(TDI-44552): tDBOutput(Snowflake) 7.1.1 to 7.3.1 migration issue
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeSchemaAndDateTypeTestIT.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
Labels: Merged build passed

#1708 fix(TDI-44192): Update dom4j to 2.1.3
  components-parent/components-bom/pom.xml
Labels: Merged build failed

#1697 fix(TDI-44578) : dbType conf over dbType in schema
  core/components-common/src/main/java/org/talend/components/common/tableaction/DefaultSQLCreateTableAction.java
  core/components-common/src/test/java/org/talend/components/common/tableaction/DefaultSQLCreateTableActionTest.java
Labels: Merged build failed

#1711 fix(TDI-44578) : dbType conf over dbType in schema (#1697)
  core/components-common/src/main/java/org/talend/components/common/tableaction/DefaultSQLCreateTableAction.java
  core/components-common/src/test/java/org/talend/components/common/tableaction/DefaultSQLCreateTableActionTest.java
Labels: Merged build failed

#1686 fix(TDI-44481): upgrade commons-beanutils to 1.9.4
  components-parent/components-bom/pom.xml
Labels: Merged build failed

#1707 fix(TDI-44498): change reduntant property name
  components/components-snowflake/components-snowflake-definition/src/main/resources/org/talend/components/snowflake/tsnowflakeinput/messages.properties
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeRuntimeIT.java
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeTestIT.java
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeWritersTestIT.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeReader.java
Labels: Merged build passed, Need review

#1714 fix(TDI-44552): make the fix not affect bulk components
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
Labels: Merged build passed

#1687 fix(TDI-44192): Update dom4j to 2.1.3
  components-parent/components-bom/pom.xml
Labels: Merged build failed

#1704 fix(TDI-44601): add json config file
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/AdditionalDatabaseSupport.java
  components/components-jdbc/components-jdbc-definition/src/main/resources/support_extra_db.json
  components/components-jdbc/components-jdbc-definition/src/test/java/org/talend/components/jdbc/AdditionalDatabaseSupportTest.java
Labels: Merged build passed

#1710 feat(TDI-44590):tsalesforceinput support bulk api v2 query
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforceinput/TSalesforceInputProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/tsalesforceinput/messages.properties
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/migration/SalesforceInputPropertiesMigrationTaskTest.java
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforceinput/TSalesforceInputPropertiesTest.java
  components/components-salesforce/components-salesforce-definition/src/test/resources/org/talend/components/salesforce/migration/tSalesforceInputProperties_721.json
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/integration/SalesforceComponentTestIT.java
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceInputBulkV2ReaderTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkExecRuntime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkQueryV2Reader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkV2ExecReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSource.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/BulkV2Connection.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/SalesforceBulkQueryV2Runtime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/SalesforceBulkV2Runtime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/request/CreateJobRequest.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/request/CreateLoadJobRequest.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/request/CreateQueryJobRequest.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/request/GetQueryJobResultRequest.java
  components/components-salesforce/components-salesforce-runtime/src/main/resources/org/talend/components/salesforce/runtime/bulk/v2/BulkV2Connection.properties
  components/components-salesforce/components-salesforce-runtime/src/main/resources/org/talend/components/salesforce/runtime/bulk/v2/SalesforceBulkQueryV2Runtime.properties
Labels: Merged build failed, Need review

#1691 TDI-44553 - Fix failing SnowflakeWriterTest (locale dependent)
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/SnowflakeWriterTest.java
Labels: Merged build passed

#1717 TDI-44553 - Fix failing SnowflakeWriterTest (locale dependent) (#1691)
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/SnowflakeWriterTest.java
Labels: Need review

#1695 fix(TDI-44393) : Support schema date pattern.
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/tsnowflakeoutput/TSnowflakeOutputProperties.java
  components/components-snowflake/components-snowflake-definition/src/main/resources/org/talend/components/snowflake/tsnowflakeoutput/messages.properties
  components/components-snowflake/components-snowflake-definition/src/test/java/org/talend/components/snowflake/tsnowflakeoutput/TSnowflakeOutputPropertiesTest.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/Formatter.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/FormatterTest.java
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/SnowflakeWriterTest.java
Labels: Merged build failed

#1719 feat(TDI-44590):tsalesforceinput support bulk api v2 query (#1710)
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforceinput/TSalesforceInputProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/tsalesforceinput/messages.properties
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/migration/SalesforceInputPropertiesMigrationTaskTest.java
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforceinput/TSalesforceInputPropertiesTest.java
  components/components-salesforce/components-salesforce-definition/src/test/resources/org/talend/components/salesforce/migration/tSalesforceInputProperties_721.json
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/integration/SalesforceComponentTestIT.java
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceInputBulkV2ReaderTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkExecRuntime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkQueryV2Reader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkV2ExecReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSource.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/BulkV2Connection.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/SalesforceBulkQueryV2Runtime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/SalesforceBulkV2Runtime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/request/CreateJobRequest.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/request/CreateLoadJobRequest.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/request/CreateQueryJobRequest.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/request/GetQueryJobResultRequest.java
  components/components-salesforce/components-salesforce-runtime/src/main/resources/org/talend/components/salesforce/runtime/bulk/v2/BulkV2Connection.properties
  components/components-salesforce/components-salesforce-runtime/src/main/resources/org/talend/components/salesforce/runtime/bulk/v2/SalesforceBulkQueryV2Runtime.properties
Labels: Merged build passed, Need review

#1721 fix(TDI-44393) : fix tSnowflakeOutputBulk regression
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
Labels: Merged build passed

#1722 chore(TDI-43011): add Jenkinsfile
  ci/Jenkinsfile
Labels: Merged build passed, Need review

#1727 chore(TDI-43011): add Jenkinsfile
  ci/Jenkinsfile
Labels: Merged build passed

#1724 feat(TDI-41936): use schema keys for upsert
  components-parent/components-bom/pom.xml
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/tsnowflakeoutput/TSnowflakeOutputProperties.java
  components/components-snowflake/components-snowflake-definition/src/main/resources/org/talend/components/snowflake/tsnowflakeoutput/messages.properties
  components/components-snowflake/components-snowflake-definition/src/test/java/org/talend/components/snowflake/tsnowflakeoutput/TSnowflakeOutputPropertiesTest.java
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeWritersTestIT.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/SnowflakeWriterTest.java
Labels: Merged build passed, Need review

#1712 Dsylaiev/tdi 44394 backport to 73
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/blob/runtime/AzureStorageGetRuntime.java
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/blob/tazurestorageget/TAzureStorageGetProperties.java
  components/components-azurestorage/src/main/resources/org/talend/components/azurestorage/blob/tazurestorageget/messages.properties
  components/components-azurestorage/src/test/java/org/talend/components/azurestorage/blob/runtime/AzureStorageGetRuntimeTest.java
Labels: Merged build passed, backport

#1723 fix(TDI-44393) : fix tSnowflakeOutputBulk regression
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
Labels: Merged build passed

#1731 chore(TDI-43011): increase timeout for splunk container
  components/components-splunk/pom.xml
Labels: Need review

#1732 chore(TDI-44145): update commons-codec:1.14
  components-parent/components-bom/pom.xml
  services/components-api-service-rest-all-components/pom.xml
  services/components-api-service-rest/pom.xml
Labels: Merged build passed
