Repository Talend/components, pull requests merged in 2020-03, with the labels that each got.

#1604 fix(TDI-43092): eliminate region ID
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeConnectionProperties.java
  components/components-snowflake/components-snowflake-definition/src/main/resources/org/talend/components/snowflake/SnowflakeConnectionProperties.properties
  components/components-snowflake/components-snowflake-definition/src/test/java/org/talend/components/snowflake/SnowflakeConnectionPropertiesTest.java
Labels: Merged build failed

#1618 fix(TDI-43612): Handling underscores in Snowflake objects names
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeAvroRegistry.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeSourceOrSink.java
  core/components-common/src/main/java/org/talend/components/common/avro/JDBCAvroRegistry.java
Labels: Merged build passed

#1619 fix(TDI-43092):fix junit test.
  components/components-snowflake/components-snowflake-definition/src/test/java/org/talend/components/snowflake/SnowflakeConnectionPropertiesTest.java
Labels: Merged build passed

#1622 fix(TDI-43629): fix issue with table action none
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
Labels: Merged build passed

#1621 fix(TDI-43820): Odd behavior using JDBC Connection in Studio
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/wizard/JDBCConnectionWizardProperties.java
Labels: Merged build failed

#1615 fix(TDI-43803): tGoogleDriveList can't list more than 100 files from a folder
  components/components-googledrive/components-googledrive-definition/src/main/java/org/talend/components/google/drive/list/GoogleDriveListProperties.java
  components/components-googledrive/components-googledrive-definition/src/main/resources/org/talend/components/google/drive/README.md
  components/components-googledrive/components-googledrive-definition/src/main/resources/org/talend/components/google/drive/list/messages.properties
  components/components-googledrive/components-googledrive-definition/src/test/java/org/talend/components/google/drive/list/GoogleDriveListPropertiesTest.java
  components/components-googledrive/components-googledrive-integration/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveListTestIT.java
  components/components-googledrive/components-googledrive-integration/src/test/java/org/talend/components/google/drive/runtime/GoogleDrivePutGetTestIT.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveAbstractListReader.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveListReader.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveValidator.java
  components/components-googledrive/components-googledrive-runtime/src/main/resources/org/talend/components/google/drive/runtime/messages.properties
  components/components-googledrive/components-googledrive-runtime/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveListReaderTest.java
Labels: Merged build passed

#1625 fix(TDI-43803): should avoid to set the default value in setupProperties method as migration not go through it
  components/components-googledrive/components-googledrive-definition/src/main/java/org/talend/components/google/drive/list/GoogleDriveListProperties.java
Labels: Merged build passed

#1626 fix(TDI-43876): Update netty codec
  components-parent/components-bom/pom.xml
Labels: Merged build passed, Need review

#1623 Dsylaiev/tdi 43218 add azure ad auth for storage
  components-parent/components-bom/pom.xml
  components/components-azurestorage/pom.xml
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/AzureConnectionWithToken.java
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/blob/runtime/AzureStorageRuntime.java
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/table/AzureStorageTableService.java
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/table/runtime/AzureStorageTableSourceOrSink.java
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/tazurestorageconnection/AuthType.java
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/tazurestorageconnection/TAzureStorageConnectionProperties.java
  components/components-azurestorage/src/main/resources/org/talend/components/azurestorage/tazurestorageconnection/messages.properties
  components/components-azurestorage/src/test/java/org/talend/components/azurestorage/AzureConnectionWithTokenTest.java
  components/components-azurestorage/src/test/java/org/talend/components/azurestorage/tazurestorageconnection/TAzureStorageConnectionPropertiesTest.java
Labels: Merged build passed

#1627 chore(TDI-43892): change COMPONENT_INSTALLER_PREFIX from installer564…
  core/components-api/src/main/java/org/talend/components/api/Constants.java
Labels: Merged build failed

#1608 TDI-43747 - Update Jython
  components/components-processing/processing-runtime/pom.xml
Labels: Merged build passed

#1605 TDI-43723 - Updating Commons Beanutils + Xerces
  components-parent/components-bom/pom.xml
  services/components-api-service-rest-all-components/pom.xml
  services/components-api-service-rest/pom.xml
Labels: Merged build passed

#1628 fix(TDI-43901): upgrade kafka version
  components-parent/components-bom/pom.xml
Labels: Merged build passed, Need review

#1633 chore:(TDI-43734): update spring version
  components-parent/components-bom/pom.xml
Labels: Merged build passed

#1637 chore(TDI-43742): update xstream
  components-parent/components-bom/pom.xml
Labels: Merged build passed

#1629 Igonchar/tdi 43912 remove bnd to spring bean name generator
  core/components-api-proptester/pom.xml
  core/components-api-proptester/src/main/java/org/talend/components/proptester/PropertiesTester.java
  core/pom.xml
  services/components-api-service-rest/src/test/java/org/talend/components/service/spring/SpringTestApp.java
Labels: Merged build passed
