Repository Talend/components, pull requests merged in 2020-01, with the labels that each got.

#1566 feat(TDI-43395):update dom4j to 2.1.1
  components-parent/components-bom/pom.xml
  components/components-marklogic/components-marklogic-runtime/pom.xml
Labels: Merged build passed, Need review

#1570 feat(TDI-43516):Salesforce api update to 47.0
  components-parent/components-bom/pom.xml
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/SalesforceConnectionProperties.java
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/integration/SalesforceComponentTestIT.java
  components/components-salesforce/components-salesforce-runtime/pom.xml
Labels: Merged build failed, Need review

#1569 fix(TDI-43509): Upgrade redshift driver
  services/components-maven-repo/config/jdbc_config.json
  services/components-maven-repo/pom.xml
Labels: Merged build passed

#1574 fix(TDI-43578): change maven central repo ulr from http to https
  components-parent/pom.xml
Labels: Merged build failed

#1579 fix(TDP-8244): fix start.bat to have OPS4J_PAX_OPTS set correctly
  services/components-api-service-rest/scripts/start.bat
Labels: Merged build passed

#1577 fix(TDI-42584): Display number of records processed for each batchId …
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
Labels: Merged build passed

#1568 Clesaec/tdi 41193 fileio outofmemory
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/SimpleFileIODatasetProperties.java
  components/components-fileio/simplefileio-definition/src/main/java/org/talend/components/simplefileio/s3/S3DatasetProperties.java
  components/components-fileio/simplefileio-definition/src/main/resources/org/talend/components/simplefileio/SimpleFileIODatasetProperties.properties
  components/components-fileio/simplefileio-definition/src/main/resources/org/talend/components/simplefileio/s3/S3DatasetProperties.properties
  components/components-fileio/simplefileio-definition/src/test/java/org/talend/components/simplefileio/SimpleFileIODatasetPropertiesTest.java
  components/components-fileio/simplefileio-definition/src/test/java/org/talend/components/simplefileio/s3/S3DatasetPropertiesTest.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/SimpleFileIOInputRuntime.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/SimpleFileIOOutputRuntime.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/SimpleRecordFormatCsvIO.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/beamcopy/ConfigurableHDFSFileSource.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/beamcopy/FileParameterException.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/beamcopy/LimitedLineRecordReader.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/s3/S3InputRuntime.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/s3/S3OutputRuntime.java
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/sources/CsvHdfsFileSource.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/simplefileio/runtime/SimpleFileIODatasetRuntimeTest.java
  components/components-fileio/simplefileio-runtime/src/test/java/org/talend/components/test/RecordSetUtil.java
Labels: Merged build passed
