Repository Talend/components, pull requests merged in 2020-04, with the labels that each got.

#1632 fix(TDI-43752): Snowflake throw warnings
  components/components-snowflake/components-snowflake-runtime/pom.xml
  core/components-api/src/main/java/org/talend/components/api/component/runtime/JarRuntimeInfo.java
Labels: Merged build passed, Need review

#1640 fix(TDI-44007): update nimbus-jose-jwt
  components-parent/components-bom/pom.xml
Labels: Merged build passed, Need review

#1641 chore(TDI-44024): update dataprep-core
  components-parent/components-bom/pom.xml
  components/components-salesforce/components-salesforce-runtime/pom.xml
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/soql/parser/SoqlBaseListener.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/soql/parser/SoqlLexer.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/soql/parser/SoqlListener.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/soql/parser/SoqlParser.java
Labels: Merged build passed

#1638 fix(TDI-43734): update spring-boot-starter version and bump daikon
  components-parent/components-bom/pom.xml
  components-parent/pom.xml
  services/components-api-service-rest-all-components/pom.xml
  services/components-api-service-rest/pom.xml
Labels: Merged build passed, Need review

#1636 fix(TDI-43946): Update logback, get dep from spring
  components-parent/components-bom/pom.xml
  services/components-api-service-rest-all-components/pom.xml
Labels: Merged build passed, Need review

#1639 TDI-44004 - Update CXF to 3.3.6
  components-parent/components-bom/pom.xml
  components-parent/pom.xml
Labels: Merged build passed

#1607 TDI-43735 - Fix Google OAuth Client configuration
  components-parent/components-bom/pom.xml
Labels: Merged build passed

#1630 fix(TDI-43721): add other custom field adapter
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/BasicMetaData.java
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/customfield/OtherCustomFieldAdapter.java
  components/components-netsuite/components-netsuite-runtime/src/test/java/org/talend/components/netsuite/client/model/customfield/CustomFieldAdaptersTest.java
Labels: Merged build failed, Need review

#1643 fix(TDI-43733):SnowflakeInput lowercase table
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeReadersTestIT.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeReader.java
Labels: Merged build passed

#1644 fix(TDI-43915): remove encryption lib from bundle
  components/components-couchbase/pom.xml
Labels: Merged build passed, Need review

#1645 fix(TDI-43176): [tNetSuiteInput] Error in retrieving Record Type when…
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/AbstractNetSuiteRuntime.java
Labels: Merged build passed
