Repository Talend/components, pull requests merged in 2020-12, with the labels that each got.

#1801 fix(TDI-44856):fix tsalesforceoutput stringoutbounds issue. (#1784)
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/dataset/SalesforceDatasetProperties.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/connection/oauth/SalesforceImplicitConnection.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkExecRuntime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkQueryInputReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceInputReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceServerTimeStampReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSink.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSource.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceWriter.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/dataprep/SalesforceDataprepSource.java
Labels: Merged build failed

#1802 fix(TDI-44856):backport to 0.23.
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/dataset/SalesforceDatasetProperties.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/connection/oauth/SalesforceImplicitConnection.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkExecRuntime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkQueryInputReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceInputReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceServerTimeStampReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSink.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSource.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceWriter.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/dataprep/SalesforceDataprepSource.java
Labels: Merged build failed

#1803 fix(TDI-44856):fix tsalesforceoutput stringoutbounds issue. (#1784)
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/dataset/SalesforceDatasetProperties.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/connection/oauth/SalesforceImplicitConnection.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkExecRuntime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkQueryInputReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceInputReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceServerTimeStampReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSink.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSource.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceWriter.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/dataprep/SalesforceDataprepSource.java
Labels: Merged build failed

#1793 fix(TDI-45268): jetty-http : Privilege Escalation
  components-parent/components-bom/pom.xml
Labels: Merged build passed

#1794 fix(TDI-45011): BP_0.28 NetSuite TCompV0: set mappings for transaction custom body fields.
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/customfield/TransactionBodyCustomFieldAdapter.java
Labels: Merged build passed, Need review

#1787 fix(TDI-45011): NetSuite TCompV0: set mappings for transaction custom body fields.
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/customfield/TransactionBodyCustomFieldAdapter.java
Labels: Merged build failed, Need review

#1811 Pyzhou/tdi 45146 t jdbc add debug message master (#1797)
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/runtime/setting/AllSetting.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/runtime/setting/JdbcRuntimeSourceOrSinkDefault.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCCloseSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCCommitSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCRollbackSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCRowSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCSPSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JdbcRuntimeUtils.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCInputReader.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCRowReader.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCSPReader.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputUpdateWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCRowWriter.java
Labels: Merged build passed

#1809 fix(TDI-45011): BP_0.27 NetSuite TCompv0 : set mappings for transaction custom body fields.
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/customfield/TransactionBodyCustomFieldAdapter.java
Labels: Merged build passed, Need review, backport

#1808 fix(TDI-45322): NetSuite TComp 0.28 - add mapping for Inventory Transfer transaction
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/customfield/TransactionBodyCustomFieldAdapter.java
Labels: Merged build passed, Need review

#1810 fix(TDI-45322): BP_Master NetSuite TCompV0: add mapping for Inventory Transfer transaction
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/customfield/TransactionBodyCustomFieldAdapter.java
Labels: Merged build failed, Need review, backport

#1813 chore(TUP-29396): add exclusion from hadoop-core
  components/components-hadoopcluster/hadoopcluster-runtime/pom.xml
Labels: Merged build failed

#1817 fix(TDI-45355):tSalesforceInput component fetches only batch size records for Big Objects
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceInputReaderTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceInputReader.java
Labels: Merged build passed, Need review

#1824 fix(TDI-45355):tSalesforceInput component fetches only batch size records for Big Objects
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceInputReaderTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceInputReader.java
Labels: Need review

#1786 fix(TDI-45223):upgrade zookeeper version.
  components-parent/components-bom/pom.xml
Labels: Merged build passed

#1826 chore(TUP-29386): exclusion jetty
  components/components-hadoopcluster/hadoopcluster-runtime/pom.xml
Labels: Merged build failed

#1798 chore(TUP-29394)CVE on guava related jars
  components-parent/components-bom/pom.xml
  components/components-hadoopcluster/hadoopcluster-runtime/src/main/java/org/apache/ambari/api/model/ApiCluster.java
  components/components-hadoopcluster/hadoopcluster-runtime/src/main/java/org/apache/ambari/api/model/ApiClusterInfo.java
  components/components-hadoopcluster/hadoopcluster-runtime/src/main/java/org/apache/ambari/api/model/ApiClusterList.java
  components/components-hadoopcluster/hadoopcluster-runtime/src/main/java/org/apache/ambari/api/model/ApiConfigFileList2.java
  components/components-hadoopcluster/hadoopcluster-runtime/src/main/java/org/apache/ambari/api/model/ApiConfigList.java
  components/components-hadoopcluster/hadoopcluster-runtime/src/main/java/org/apache/ambari/api/model/ApiListBase.java
  components/components-hadoopcluster/hadoopcluster-runtime/src/main/java/org/apache/ambari/api/model/ApiService.java
  components/components-hadoopcluster/hadoopcluster-runtime/src/main/java/org/apache/ambari/api/model/ApiServiceInfo.java
  components/components-hadoopcluster/hadoopcluster-runtime/src/main/java/org/apache/ambari/api/model/ApiServiceList.java
Labels: Merged build failed

#1814 fix(TDI-45311):upgrade guava version.
  components-parent/components-bom/pom.xml
  core/components-osgi-test/components-osgitest/pom.xml
  core/components-osgi-test/components-osgitest/src/main/java/org/talend/components/api/ComponentsPaxExamOptions.java
Labels: Merged build passed

#1790 fix(TDI-45265): Dynamic type with Delta lake
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/runtime/setting/JDBCSQLBuilder.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/type/RowWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputDeleteWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputInsertOrUpdateWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputInsertWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputUpdateOrInsertWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputUpdateWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputWriter.java
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/JDBCOutputTestIT.java
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/common/DBTestUtils.java
Labels: Merged build passed

#1789 fix(TDI-45265): Dynamic type with Delta lake
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/runtime/setting/JDBCSQLBuilder.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/type/RowWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputDeleteWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputInsertOrUpdateWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputInsertWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputUpdateOrInsertWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputUpdateWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputWriter.java
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/JDBCOutputTestIT.java
  components/components-jdbc/components-jdbc-runtime/src/test/java/org/talend/components/jdbc/common/DBTestUtils.java
Labels: Merged build failed

#1823 fix(TDI-45356): Align version of "httpclient" and "httpcore" dependencies.
  components-parent/components-bom/pom.xml
  services/components-api-service-rest/pom.xml
Labels: Merged build failed, Need review

#1830 fix(TDI-45356): BP: Align version of "httpclient" and "httpcore" dependencies.
  components-parent/components-bom/pom.xml
Labels: Need review, backport
