Repository Talend/components, pull requests merged in 2020-09, with the labels that each got.

#1733 feat(TDI-44730): upgrade driver to latest one
  components-parent/components-bom/pom.xml
Labels: Merged build passed, Need review

#1736 chore(TDI-44145): add note
  components-parent/components-bom/pom.xml
Labels: Merged build passed

#1738 feat(TDI-44730): update maven repo project
  services/components-maven-repo/config/jdbc_config.json
  services/components-maven-repo/pom.xml
Labels: Need review

#1740 fix(TDI-43729): Update Tika version to 1.24.1
  components/components-fileio/simplefileio-runtime/pom.xml
Labels: Merged build passed

#1741 TDI-44819 - Disable DTDs when checking excel files
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/hadoop/excel/streaming/StreamingWorkbookReader.java
Labels: Merged build passed

#1674 TDI-44386 - Update Talend proxy to 1.0.1
  components-parent/components-bom/pom.xml
Labels: Merged build failed

#1745 fix(TDI-44795):Salesforce query using toLabel() in query mode = "Bulk" fails with error
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceInputReaderTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkQueryInputReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
Labels: Merged build failed, Need review

#1746 fix(TDI-44795):Salesforce query using toLabel() in query mode = "Bulk" fails with error(#1745)
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceInputReaderTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkQueryInputReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
Labels: Need review

#1737 chore: upgrade snakeyaml version
  components-parent/components-bom/pom.xml
  services/components-api-service-rest-all-components/pom.xml
  services/components-api-service-rest/pom.xml
Labels: Merged build passed, Need review

#1617 TDI-43809 - Update Snakeyaml
  components-parent/components-bom/pom.xml
  services/components-api-service-rest-all-components/pom.xml
  services/components-api-service-rest/pom.xml
Labels: Merged build failed

#1748 chore(TDI-44859): add version for felix dependency (#1747)
  core/components-osgi-test/components-osgitest/src/main/java/org/talend/components/api/ComponentsPaxExamOptions.java
Labels: Need review, backport

#1743 feat(TUP-27654):Databricks Delta Lake - Support ELT & MERGE
  components/components-jdbc/components-jdbc-definition/src/main/resources/support_extra_db.json
Labels: Merged build passed

#1742 feat(TUP-27654):Databricks Delta Lake - Support ELT & MERGE
  components/components-jdbc/components-jdbc-definition/src/main/resources/support_extra_db.json
Labels: Merged build passed

#1709 fix(TDI-44394): Add keep remote dir structure checkbox
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/blob/runtime/AzureStorageGetRuntime.java
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/blob/tazurestorageget/TAzureStorageGetProperties.java
  components/components-azurestorage/src/main/resources/org/talend/components/azurestorage/blob/tazurestorageget/messages.properties
  components/components-azurestorage/src/test/java/org/talend/components/azurestorage/blob/runtime/AzureStorageGetRuntimeTest.java
Labels: Merged build passed, Need review
