Repository Talend/components, pull requests merged in 2020-10, with the labels that each got.

#1752 feat(TDI-44718): snowflake OAuth2 password grant type
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeConnectionProperties.java
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeOauthConnectionProperties.java
  components/components-snowflake/components-snowflake-definition/src/main/resources/org/talend/components/snowflake/SnowflakeOauthConnectionProperties.properties
  components/components-snowflake/components-snowflake-definition/src/test/java/org/talend/components/snowflake/SnowflakeOauthConnectionPropertiesTest.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeSourceOrSink.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/utils/OauthTokenUtils.java
Labels: Merged build passed, Need review

#1755 feat(TDI-44718): snowflake OAuth2 password grant type (#1752)
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeConnectionProperties.java
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeOauthConnectionProperties.java
  components/components-snowflake/components-snowflake-definition/src/main/resources/org/talend/components/snowflake/SnowflakeOauthConnectionProperties.properties
  components/components-snowflake/components-snowflake-definition/src/test/java/org/talend/components/snowflake/SnowflakeOauthConnectionPropertiesTest.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeSourceOrSink.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/utils/OauthTokenUtils.java
Labels: Merged build failed, backport

#1753 fix(TUP-26310): Odd behavior using JDBC Connection in Studio (#1621)
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/wizard/JDBCConnectionWizardProperties.java
Labels: Merged build passed

#1754 feat(TUP-28640):Improve JDBC database support framework to load suppo…
  components/components-jdbc/components-jdbc-definition/src/main/resources/support_extra_db.json
Labels: Merged build failed

#1761 Update support_extra_db.json
  components/components-jdbc/components-jdbc-definition/src/main/resources/support_extra_db.json
Labels: Merged build passed

#1765 Pyzhou/tdi 41731 t jira escape issue master
  components/components-jira/src/main/java/org/talend/components/jira/datum/EntityParser.java
  components/components-jira/src/test/java/org/talend/components/jira/datum/SearchTest.java
Labels: Merged build passed
