Repository Talend/components, pull requests merged in 2020-11, with the labels that each got.

#1769 fix(TDI-44862): Update Spark to 2.4.6 for cloud env test
  components-parent/components-bom/pom.xml
  core/components-adapter-beam-parent/pom.xml
Labels: Merged build passed

#1768 chore(TDI-44994): bump version for google oauth client
  components-parent/components-bom/pom.xml
Labels: Merged build passed, Need review

#1766 fix(TDI-44910): Add memsql support in studio
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/AdditionalDatabaseSupport.java
  components/components-jdbc/components-jdbc-definition/src/main/resources/support_extra_db.json
  components/components-jdbc/components-jdbc-definition/src/test/java/org/talend/components/jdbc/AdditionalDatabaseSupportTest.java
Labels: Merged build passed

#1770 chore(TDI-44004): update cxf to 3.3.7
  components-parent/components-bom/pom.xml
  components-parent/pom.xml
Labels: Merged build passed

#1778 fix(TDI-45169): NumberFormatException with S3 dataset and tcomp 0.28.x
  components/components-fileio/simplefileio-runtime/src/main/java/org/talend/components/simplefileio/runtime/s3/S3Connection.java
Labels: Merged build failed

#1763 fix(TDI-44910): Add memsql support in studio
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/AdditionalDatabaseSupport.java
  components/components-jdbc/components-jdbc-definition/src/main/resources/support_extra_db.json
  components/components-jdbc/components-jdbc-definition/src/test/java/org/talend/components/jdbc/AdditionalDatabaseSupportTest.java
Labels: Merged build failed

#1777 TDI-44227 : veracode
  ci/Jenkinsfile-scan
Labels: Merged build passed

#1792 TDI-45274 : Correct usage of kubernetes
  ci/Jenkinsfile
Labels: Merged build passed

#1791 chore(TDI-45243): update xstream to 1.4.14
  components-parent/components-bom/pom.xml
Labels: Merged build failed

#1785 fix(TDI-45232): upgrade aws s3 library
  components-parent/components-bom/pom.xml
Labels: Merged build failed, Need review

#1795 fix(TDI-45232): upgrade aws s3 library (#1785)
  components-parent/components-bom/pom.xml
Labels: backport

#1797 Pyzhou/tdi 45146 t jdbc add debug message master
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/runtime/setting/AllSetting.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/runtime/setting/JdbcRuntimeSourceOrSinkDefault.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCCloseSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCCommitSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCRollbackSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCRowSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCSPSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JdbcRuntimeUtils.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCInputReader.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCRowReader.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCSPReader.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputUpdateWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCRowWriter.java
Labels: Merged build failed

#1776 fix(TDI-45146):Add debug message
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/runtime/setting/AllSetting.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/runtime/setting/JdbcRuntimeSourceOrSinkDefault.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCCloseSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCCommitSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCRollbackSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCRowSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCSPSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JdbcRuntimeUtils.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCInputReader.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCRowReader.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCSPReader.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputUpdateWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCRowWriter.java
Labels: Merged build passed

#1796 correct the repository
  components/components-marklogic/components-marklogic-runtime/pom.xml
Labels: Merged build failed

#1784 fix(TDI-44856):fix tsalesforceoutput stringoutbounds issue.
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/dataset/SalesforceDatasetProperties.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/connection/oauth/SalesforceImplicitConnection.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkExecRuntime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkQueryInputReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceInputReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceServerTimeStampReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSink.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSource.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceWriter.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/dataprep/SalesforceDataprepSource.java
Labels: Merged build passed
