Repository Talend/components, pull requests merged in 2020-07, with the labels that each got.

#1681 fix(TDI-44413): fix big date values
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeDateTypeTestIT.java
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeRuntimeIT.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/SnowflakeWriterTest.java
Labels: Merged build failed, Need review

#1684 fix(TDI-44413): fix big date values (#1681)
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeDateTypeTestIT.java
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeRuntimeIT.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/SnowflakeWriterTest.java
Labels: Merged build failed, Need review

#1680 Igonchar/tdi 44235 2 release script (#1676)
  release.sh
Labels: Merged build failed

#1685 fix(TDI-44468): revert fix of TDI-37641
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputDefinition.java
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputProperties.java
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputDefinitionTest.java
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputPropertiesTest.java
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceAnyTypeFieldTestIT.java
Labels: Merged build failed, Need review

#1694 fix(TDI-44468): revert fix of TDI-37641
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputDefinition.java
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputProperties.java
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputDefinitionTest.java
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforceoutput/TSalesforceOutputPropertiesTest.java
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceAnyTypeFieldTestIT.java
Labels: Merged build failed, Need review

#1688 fix(TDI-41286): set default values
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeDbTypeProperties.java
  components/components-snowflake/components-snowflake-definition/src/test/java/org/talend/components/snowflake/tsnowflakeoutput/TSnowflakeOutputPropertiesTest.java
Labels: Merged build passed

#1698 fix(TDI-41286): set default values
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/SnowflakeDbTypeProperties.java
  components/components-snowflake/components-snowflake-definition/src/test/java/org/talend/components/snowflake/tsnowflakeoutput/TSnowflakeOutputPropertiesTest.java
Labels: Merged build passed

#1690 fix(TDI-44497): upsert key column
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeWritersTestIT.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
Labels: Merged build passed, Need review

#1699 fix(TDI-44497): upsert key column (#1690)
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeWritersTestIT.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
Labels: Need review

#1683 fix(TDI-43606): set default values for trim
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcinput/TJDBCInputProperties.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCInputReader.java
Labels: Merged build passed

#1700 fix(TDI-43606): set default values for trim
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcinput/TJDBCInputProperties.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCInputReader.java
Labels: Merged build passed

#1693 fix(TDI-44498): escape column names
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeRuntimeIT.java
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeTestIT.java
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeWritersTestIT.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeReader.java
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/SnowflakeReaderTest.java
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/SnowflakeWriterTest.java
Labels: Merged build passed, Need review

#1706 Revert "fix(TDI-44498): escape column names"
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeRuntimeIT.java
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeTestIT.java
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeWritersTestIT.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeReader.java
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/SnowflakeReaderTest.java
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/SnowflakeWriterTest.java
Labels: Merged build failed
