Repository Talend/components, pull requests merged in 2021-03, with the labels that each got.

#1869 chore(TDI-43892): change COMPONENT_INSTALLER_PREFIX from installer
  core/components-api/src/main/java/org/talend/components/api/Constants.java
Labels: Merged build failed

#1871 fix(TDI-45487): support jdbc bulkexec components for singlestore in studio
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/JDBCFamilyDefinition.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/module/BulkModule.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/runtime/setting/AllSetting.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcbulkexec/TJDBCBulkExecDefinition.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcbulkexec/TJDBCBulkExecProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcoutputbulk/TJDBCOutputBulkDefinition.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcoutputbulk/TJDBCOutputBulkProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcoutputbulkexec/TJDBCOutputBulkExecDefinition.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcoutputbulkexec/TJDBCOutputBulkExecProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/module/BulkModule.properties
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcbulkexec/messages.properties
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcbulkexec/tJDBCBulkExec_icon32.png
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcoutputbulk/messages.properties
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcoutputbulk/tJDBCOutputBulk_icon32.png
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcoutputbulkexec/messages.properties
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcoutputbulkexec/tJDBCOutputBulkExec_icon32.png
  components/components-jdbc/components-jdbc-definition/src/main/resources/support_extra_db.json
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCBulkExecRuntime.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCBulkFileRuntime.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCBulkFileWriteOperation.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCBulkFileWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JdbcRuntimeUtils.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/type/BulkFormatter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/type/RowWriter.java
Labels: Merged build passed

#1865 fix(TDI-45418):Upgrade Jackson libraries
  components-parent/components-bom/pom.xml
Labels: Merged build failed

#1872 fix(TDI-45418):Upgrade Jackson libraries
  components-parent/components-bom/pom.xml
Labels: Merged build failed

#1876 fix(TDI-45696): Jersey-media-jaxb: XML Entity Expansion (XEE) in Talend/components (master)
  core/components-adapter-beam/pom.xml
Labels: Merged build passed

#1880 Update Jenkinsfile-scan
  ci/Jenkinsfile-scan
Labels: Merged build passed

#1878 fix(TDI-45727): CVE jackson-mapper-asl
  components-parent/components-bom/pom.xml
Labels: Merged build passed

#1886 feat(TDI-44490):Option to specify parent object in tSalesforceInput when PK Chunking is enabled.
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforceinput/TSalesforceInputProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/tsalesforceinput/messages.properties
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforceinput/TSalesforceInputPropertiesTest.java
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceInputReaderTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
Labels: Merged build passed, Need review

#1866 feat(TDI-45335): Bypass rate limit on docker hub
  ci/Jenkinsfile
  components-parent/pom.xml
  components/components-couchbase/pom.xml
  components/components-jira/pom.xml
  components/components-splunk/pom.xml
Labels: Merged build passed
