Repository Talend/components, pull requests merged in 2021-06, with the labels that each got.

#1927 fix(TDI-46109): update XStream to 1.4.17
  components-parent/components-bom/pom.xml
Labels: Merged build failed, Need review

#1925 fix(TDI-46131): Missing jar for snowflake
  components/components-snowflake/components-snowflake-runtime/pom.xml
Labels: Merged build failed, Need review

#1924 TDI-46133 - Switch Beam GeneratorFunction to use SHA-256 instead of MD5
  core/components-adapter-beam/src/main/java/org/talend/components/adapter/beam/io/rowgenerator/GeneratorFunction.java
Labels: Merged build passed

#1928 fix(TDI-46220): upgrade json-smart to 2.4.7 for CVE
  components-parent/components-bom/pom.xml
Labels: Merged build failed

#1921 chore(TDI-46067): Bump commons-lang3
  components-parent/components-bom/pom.xml
Labels: Merged build failed, Need review
