Repository Talend/components, pull requests merged in 2021-04, with the labels that each got.

#1881 feat(TDI-45762):update snowflake-jdbc version.
  components-parent/components-bom/pom.xml
Labels: Merged build passed

#1885 feat(TDI-43755):Allow "include deleted records" option to be available on the tSalesforceInput component on Bulk Query mode
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforceinput/TSalesforceInputProperties.java
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforceinput/TSalesforceInputPropertiesTest.java
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceInputReaderTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkQueryInputReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/SalesforceBulkQueryV2Runtime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/dataprep/SalesforceBulkQueryReader.java
Labels: Merged build passed, Need review

#1883 fix(TDI-45723): Sanitize MLCP command string (Use ProcessBuilder)
  components/components-marklogic/components-marklogic-runtime/src/main/java/org/talend/components/marklogic/runtime/bulkload/AbstractMarkLogicBulkLoadRunner.java
  components/components-marklogic/components-marklogic-runtime/src/main/java/org/talend/components/marklogic/runtime/bulkload/MarkLogicExternalBulkLoadRunner.java
  components/components-marklogic/components-marklogic-runtime/src/main/java/org/talend/components/marklogic/runtime/bulkload/MarkLogicInternalBulkLoadRunner.java
  components/components-marklogic/components-marklogic-runtime/src/main/java/org/talend/components/marklogic/util/CommandExecutor.java
  components/components-marklogic/components-marklogic-runtime/src/test/java/org/talend/components/marklogic/runtime/bulkload/MarkLogicExternalBulkLoadRunnerTest.java
  components/components-marklogic/components-marklogic-runtime/src/test/java/org/talend/components/marklogic/runtime/bulkload/MarkLogicInternalBulkLoadRunnerTest.java
Labels: Merged build passed, Work in progress(do not merge)

#1890 chore(TDI-45839): cve bump junit
  components-parent/components-bom/pom.xml
Labels: Merged build passed

#1882 fix(TDI-45790): fix delete operation
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/output/NsObjectOutputTransducer.java
  components/components-netsuite/components-netsuite-runtime_2019_2/src/test/java/org/talend/components/netsuite/v2019_2/output/NetSuiteOutputWriterIT.java
Labels: Merged build passed

#1891 fix(TDI-45815): CVE: xstream-1.4.15.jar
  components-parent/components-bom/pom.xml
Labels: Merged build passed

#1893 feat(TDI-44956):Salesforce connection with Mutual auth for basic connection type.
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/SalesforceConnectionProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/SalesforceSSLProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/SalesforceSSLProperties.properties
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/test/SalesforceConnectionPropertiesTest.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.java
Labels: Merged build passed, Need review

#1889 fix(TDI-45838): Set locator when not chunking read not everything
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/BulkV2Connection.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/SalesforceBulkQueryV2Runtime.java
  components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/runtime/bulk/v2/SalesforceBulkQueryV2RuntimeTest.java
Labels: Merged build passed, Need review

#1903 fix(TDI-45883): CVE: calcite-core-1.16.0.jar
  components-parent/components-bom/pom.xml
Labels: Merged build passed

#1901 chore(TDI-45945): cve httpclient to [4.5.13]
  components-parent/components-bom/pom.xml
Labels: Merged build passed

#1815 fix(TDI-43011): Migrate component jobs jenkins1 to jenkins2
  ci/Jenkinsfile
  components/components-jira/pom.xml
  components/components-splunk/pom.xml
Labels: Merged build failed

#1909 fix(TDI-45883): CVE: calcite-core-1.16.0.jar
  components-parent/components-bom/pom.xml
  components/components-jdbc/components-jdbc-definition/pom.xml
Labels: Merged build passed

#1907 feat(TDI-44945):Snowflake DB Output Die on Error
  components/components-snowflake/components-snowflake-definition/src/main/java/org/talend/components/snowflake/tsnowflakeoutput/TSnowflakeOutputProperties.java
  components/components-snowflake/components-snowflake-definition/src/main/resources/org/talend/components/snowflake/tsnowflakeoutput/messages.properties
  components/components-snowflake/components-snowflake-integration/src/test/java/org/talend/components/snowflake/test/SnowflakeWritersTestIT.java
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeWriter.java
Labels: Merged build passed, Need review

#1897 feat(TDI-45716):improve error messages on multiple statements.
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/runtime/setting/AllSetting.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcrow/TJDBCRowProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcrow/messages.properties
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCRowSourceOrSink.java
Labels: Merged build passed

#1902 fix(TDI-45821): CVE: json-smart-2.2.1.jar
  components-parent/components-bom/pom.xml
Labels: Merged build passed

#1899 chore(TDI-45908): junit as test dep for marklogic
  components/components-marklogic/components-marklogic-definition/pom.xml
  components/components-marklogic/components-marklogic-runtime/pom.xml
Labels: Merged build passed

#1911 fix(TDI-43011): add setting xml for deploy
  ci/Jenkinsfile
  ci/settings.xml
Labels: Merged build passed

#1887 Pyzhou/TDI-42451 salesforce bulk support json
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforcebulkexec/TSalesforceBulkExecProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/tsalesforceoutputbulkexec/TSalesforceOutputBulkExecProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/tsalesforcebulkexec/messages.properties
  components/components-salesforce/components-salesforce-definition/src/test/java/org/talend/components/salesforce/tsalesforcebulkexec/TSalesforceBulkExecPropertiesTest.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkExecReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkExecRuntime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
  components/components-salesforce/components-salesforce-runtime/src/main/resources/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.properties
  components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/runtime/SalesforceBulkLoadJSONTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/test/SalesforceRuntimeTestUtil.java
Labels: Merged build passed

#1900 fix(TDI-45899): Delete custom transactional record.
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/output/NsObjectOutputTransducer.java
  components/components-netsuite/components-netsuite-runtime/src/test/java/org/talend/components/netsuite/AbstractNetSuiteTestBase.java
  components/components-netsuite/components-netsuite-runtime/src/test/java/org/talend/components/netsuite/output/NetSuiteOutputTransducerTest.java
  components/components-netsuite/components-netsuite-runtime/src/test/java/org/talend/components/netsuite/test/TestUtils.java
  components/components-netsuite/components-netsuite-runtime/src/test/resources/test-data/customTransaction-1.json
Labels: Merged build passed, Need review
