Repository Talend/components, pull requests merged in 2021-01, with the labels that each got.

#1832 fix(TDI-36042): Friendly connection error message
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.java
  components/components-salesforce/components-salesforce-runtime/src/main/resources/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.properties
Labels: Merged build failed

#1836 fix(TDI-36042):Firendly message for Salesforce TEST FIX
  components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/runtime/SalesforceSessionReuseTestIT.java
Labels: Merged build passed

#1842 Merge pull request #1832 from Talend/ovladyka/TDI-36042_Freindly_conn…
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.java
  components/components-salesforce/components-salesforce-runtime/src/main/resources/org/talend/components/salesforce/runtime/SalesforceSourceOrSink.properties
  components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/runtime/SalesforceSessionReuseTestIT.java
Labels: Merged build failed, backport

#1846 fix(TDI-45489): Components - update nimbus-jose-jwt
  components-parent/components-bom/pom.xml
Labels: Merged build failed, Need review, backport

#1834 fix(TDI-45447): Upgrade bouncycastle
  components-parent/components-bom/pom.xml
Labels: Merged build passed

#1831 fix(TDI-45436):upgrade xstream
  components-parent/components-bom/pom.xml
Labels: Merged build passed

#1829 fix(TDI-45418):Upgrade Jackson libraries
  components-parent/components-bom/pom.xml
Labels: Merged build passed

#1833 fix(TDI-45432): upgrade google cloud family and align with tbigquery in studio
  components-parent/components-bom/pom.xml
Labels: Merged build failed

#1835 fix(TDI-45432): tBigQueryOutput fails when the checkbox "Create the table if it doesn't exist" is ticked
  components-parent/components-bom/pom.xml
Labels: Merged build passed

#1850 feat(TUP-29701): Upgrade eclipse 418
  core/components-api/src/main/java/org/talend/components/api/component/runtime/JarRuntimeInfo.java
Labels: Merged build passed

#1848 fix(TDI-45526):tSalesforceOutputBulkExec using Bulk V2 crashes when zero
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceBulkExecReaderTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkV2ExecReader.java
Labels: Merged build failed, Need review

#1852 fix(TDI-45526):tSalesforceOutputBulkExec using Bulk V2 crashes when zero records.(#1848)
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceBulkExecReaderTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkV2ExecReader.java
Labels: Need review

#1849 feat(TDI-42274):Add Safety Switch checkbox for tSalesforceOutputBulkExec
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/SalesforceBulkProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/SalesforceBulkProperties.properties
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceBulkExecReaderTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkExecReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkV2ExecReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/SalesforceBulkV2Runtime.java
Labels: Merged build passed, Need review

#1845 fix(TDI-45505): "useDataSource" property is not processed by tJDBCOutput correctly
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcoutput/TJDBCOutputProperties.java
Labels: Merged build failed

#1853 feat(TDI-42274):Add Safety Switch checkbox for tSalesforceOutputBulkExec (#1849)
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/SalesforceBulkProperties.java
  components/components-salesforce/components-salesforce-definition/src/main/resources/org/talend/components/salesforce/SalesforceBulkProperties.properties
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceBulkExecReaderTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkExecReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkV2ExecReader.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/SalesforceBulkV2Runtime.java
Labels: Merged build passed, Need review
