Repository Talend/components, pull requests merged in 2021-02, with the labels that each got.

#1855 fix(TDI-45593): Do not throw error when container name is numerical
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/blob/runtime/AzureStorageContainerRuntime.java
  components/components-azurestorage/src/test/java/org/talend/components/azurestorage/blob/runtime/AzureStorageContainerRuntimeTest.java
Labels: Merged build passed

#1859 fix(TDI-45593): Do not throw error when container name is numerical (…
  components/components-azurestorage/src/main/java/org/talend/components/azurestorage/blob/runtime/AzureStorageContainerRuntime.java
  components/components-azurestorage/src/test/java/org/talend/components/azurestorage/blob/runtime/AzureStorageContainerRuntimeTest.java
Labels: Merged build passed, Need review, backport

#1857 chore(TDI-45608): upgrade snowflake version
  components-parent/components-bom/pom.xml
Labels: Need review, Work in progress(do not merge)

#1854 fix(TDI-45495): backport fix to tcomp
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/NsObjectTransducer.java
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/customfield/ListOrRecord.java
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/customfield/MultiSelectCustomField.java
Labels: Merged build passed, Need review

#1861 fix(TDI-45495): backport fix to tcomp (#1854)
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/NsObjectTransducer.java
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/customfield/ListOrRecord.java
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/customfield/MultiSelectCustomField.java
Labels: Need review, backport

#1863 fix(TDI-45664): meet an build issue when build studio patch for 7.3.1
  components/components-marketo/components-marketo-runtime/pom.xml
Labels: Merged build passed

#1860 fix(TDI-45637): other custom fields support
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/BasicMetaData.java
  components/components-netsuite/components-netsuite-runtime/src/main/java/org/talend/components/netsuite/client/model/customfield/OtherCustomFieldAdapter.java
  components/components-netsuite/components-netsuite-runtime/src/test/java/org/talend/components/netsuite/client/model/customfield/CustomFieldAdaptersTest.java
Labels: Merged build failed, Need review

#1862 fix(TDI-45644): tGoogleDriveGet Read Timeout
  components/components-googledrive/components-googledrive-definition/src/main/java/org/talend/components/google/drive/connection/GoogleDriveConnectionProperties.java
  components/components-googledrive/components-googledrive-definition/src/main/resources/org/talend/components/google/drive/connection/messages.properties
  components/components-googledrive/components-googledrive-definition/src/test/java/org/talend/components/google/drive/connection/GoogleDriveConnectionPropertiesTest.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveRuntime.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/client/GoogleDriveService.java
Labels: Merged build passed, Need review

#1867 fix(TDI-45644): tGoogleDriveGet Read Timeout (#1862)
  components/components-googledrive/components-googledrive-definition/src/main/java/org/talend/components/google/drive/connection/GoogleDriveConnectionProperties.java
  components/components-googledrive/components-googledrive-definition/src/main/resources/org/talend/components/google/drive/connection/messages.properties
  components/components-googledrive/components-googledrive-definition/src/test/java/org/talend/components/google/drive/connection/GoogleDriveConnectionPropertiesTest.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveRuntime.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/client/GoogleDriveService.java
Labels: Merged build passed, backport

#1868 Dchmyga/tdi 45644 google drive read timeout backport
  components/components-googledrive/components-googledrive-definition/src/main/java/org/talend/components/google/drive/connection/GoogleDriveConnectionProperties.java
  components/components-googledrive/components-googledrive-definition/src/main/resources/org/talend/components/google/drive/connection/messages.properties
  components/components-googledrive/components-googledrive-definition/src/test/java/org/talend/components/google/drive/connection/GoogleDriveConnectionPropertiesTest.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveRuntime.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/client/GoogleDriveService.java
Labels: Merged build passed, backport
