Repository Talend/components, pull requests merged in 2021-11, with the labels that each got.

#1982 fix(TDI-46887): CVE - update "jena-core" to 4.2.0
  components-parent/components-bom/pom.xml
Labels: Merged build failed, Need review

#1981 fix(TDI-46753) CVE - update "glassfish-jersey" dependencies to 2.33
  components-parent/components-bom/pom.xml
Labels: Merged build failed, Need review

#1985 fix(TDI-46963): Do not import javax.servlet into bundle
  components/components-azurestorage/pom.xml
Labels: Merged build failed, Need review

#1984 feat(TDI-45016):add query timeout to jdbc.
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/runtime/setting/AllSetting.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcinput/TJDBCInputProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcoutput/TJDBCOutputProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcrow/TJDBCRowProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcinput/messages.properties
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcoutput/messages.properties
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcrow/messages.properties
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCRowSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCInputReader.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCRowReader.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCRowWriter.java
Labels: Merged build failed

#1987 feat(TDI-45016): add query timeout to jdbc
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/runtime/setting/AllSetting.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcinput/TJDBCInputProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcoutput/TJDBCOutputProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcrow/TJDBCRowProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcinput/messages.properties
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcoutput/messages.properties
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcrow/messages.properties
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCRowSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCInputReader.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCRowReader.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCRowWriter.java
Labels: Merged build failed

#1988 fix(TDI-46746): backport for branch "maintenance/8.0"
  components-parent/components-bom/pom.xml
  components/components-marklogic/components-marklogic-runtime/pom.xml
Labels: Merged build failed, Need review, backport

#1989 fix(TDI-46746): backport for branch "maintenance/7.3"
  components-parent/components-bom/pom.xml
  components/components-marklogic/components-marklogic-runtime/pom.xml
Labels: Merged build failed, Need review, backport

#1991 fix(TDI-46753): backport to "maintenance/8.0" branch
  components-parent/components-bom/pom.xml
Labels: Merged build failed, Need review, backport

#1990 fix(TDI-46753): backport to "maintenance/7.3" branch
  components-parent/components-bom/pom.xml
Labels: Merged build failed, Need review, backport

#1992 fix(TDI-46887): backport to "maintenance/8.0" branch.
  components-parent/components-bom/pom.xml
Labels: Merged build failed, Need review, backport

#1995 feat(TDI-45016):add query timeout to jdbc. (#1984)
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/runtime/setting/AllSetting.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcinput/TJDBCInputProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcoutput/TJDBCOutputProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcrow/TJDBCRowProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcinput/messages.properties
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcoutput/messages.properties
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcrow/messages.properties
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCRowSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCInputReader.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCRowReader.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCRowWriter.java
Labels: Merged build failed

#1996 Revert "feat(TDI-45016):add query timeout to jdbc. (#1984)"
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/runtime/setting/AllSetting.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcinput/TJDBCInputProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcoutput/TJDBCOutputProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcrow/TJDBCRowProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcinput/messages.properties
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcoutput/messages.properties
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcrow/messages.properties
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCRowSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCInputReader.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCRowReader.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCRowWriter.java
Labels: Merged build failed

#1997 feat(TDI-45016):add query timeout and fix NPE in its
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/runtime/setting/AllSetting.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcinput/TJDBCInputProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcoutput/TJDBCOutputProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/tjdbcrow/TJDBCRowProperties.java
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcinput/messages.properties
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcoutput/messages.properties
  components/components-jdbc/components-jdbc-definition/src/main/resources/org/talend/components/jdbc/tjdbcrow/messages.properties
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCRowSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCSourceOrSink.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCInputReader.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/reader/JDBCRowReader.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCOutputWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/writer/JDBCRowWriter.java
Labels: Merged build failed
