Repository Talend/components, pull requests merged in 2021-12, with the labels that each got.

#1994 fix(TDI-47005): tsalesforceoutput component update didn't work same with upsert that column name case insensitive
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/integration/SalesforceTestBase.java
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceInputBulkV2ReaderTestIT.java
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceInputReaderTestIT.java
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceWriterTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceWriter.java
  components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/runtime/SalesforceSessionReuseTestIT.java
Labels: Merged build failed, Need review

#1998 fix(TDI-47005): tsalesforceoutput component update didn't work same with upsert that column name case insensitive (#1994)
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/integration/SalesforceTestBase.java
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceInputBulkV2ReaderTestIT.java
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceInputReaderTestIT.java
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/runtime/SalesforceWriterTestIT.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceWriter.java
  components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/runtime/SalesforceSessionReuseTestIT.java
Labels: Merged build failed, Need review

#1999 fix(TDI-47178):[Jenkins][TCOMPv0] Need to make sure jenkins build deploy jars automaticly
  ci/Jenkinsfile
Labels: Merged build failed, Need review

#1993 fix(TDI-47122): Metadata details are not loaded from Snowflake
  components/components-snowflake/components-snowflake-runtime/src/main/java/org/talend/components/snowflake/runtime/SnowflakeAvroRegistry.java
  components/components-snowflake/components-snowflake-runtime/src/test/java/org/talend/components/snowflake/runtime/SnowflakeAvroRegistryTest.java
Labels: Merged build failed

#2003 fix(TDI-47269): CVE - update "jena-core" to 4.2.0
  components-parent/components-bom/pom.xml
Labels: Merged build failed, Need review, backport

#2002 fix(TDI-47212): CVE: jackson-mapper(core)-asl-1.9.15-TALEND
  components-parent/components-bom/pom.xml
Labels: Merged build failed

#1986 fix(TDI-46665): support java 17
  components-parent/components-bom/pom.xml
  components-parent/pom.xml
  components/components-couchbase/pom.xml
  components/components-googledrive/pom.xml
  components/components-hadoopcluster/pom.xml
  components/components-jdbc/components-jdbc-integration/src/test/java/org/talend/components/jdbc/integration/JdbcRowTestIT.java
  components/components-jdbc/pom.xml
  components/components-marketo/pom.xml
  components/components-marklogic/pom.xml
  components/components-netsuite/pom.xml
  components/components-salesforce/pom.xml
  components/components-snowflake/pom.xml
  core/components-adapter-beam-parent/pom.xml
  core/components-api/pom.xml
  core/components-api/src/main/java/org/talend/components/api/component/runtime/JarRuntimeInfo.java
  examples/components-api-archetypes/bd-component-archetype/src/main/resources/archetype-resources/pom.xml
  examples/components-api-archetypes/input-component-archetype/src/main/resources/archetype-resources/pom.xml
Labels: Merged build failed

#2006 fix(TDI-47269):degrate jena version to 2.13.0
  components-parent/components-bom/pom.xml
  components/components-marklogic/components-marklogic-runtime/pom.xml
Labels: Need review

#1965 feat(TDI-46806): Update azureSDK for tcompv0
  components-parent/components-bom/pom.xml
Labels: Merged build failed, Need review
