Repository Talend/components, pull requests merged in 2021-10, with the labels that each got.

#1957 fix(TDI-46756): update XStream to 1.4.18
  components-parent/components-bom/pom.xml
Labels: Merged build failed, Need review

#1949 feat(TDI-45110): Access "Shared drives" with GoogleDrive components
  components/components-googledrive/components-googledrive-definition/src/main/java/org/talend/components/google/drive/GoogleDriveComponentProperties.java
  components/components-googledrive/components-googledrive-definition/src/main/java/org/talend/components/google/drive/copy/GoogleDriveCopyProperties.java
  components/components-googledrive/components-googledrive-definition/src/main/java/org/talend/components/google/drive/create/GoogleDriveCreateProperties.java
  components/components-googledrive/components-googledrive-definition/src/main/java/org/talend/components/google/drive/delete/GoogleDriveDeleteProperties.java
  components/components-googledrive/components-googledrive-definition/src/main/java/org/talend/components/google/drive/get/GoogleDriveGetProperties.java
  components/components-googledrive/components-googledrive-definition/src/main/java/org/talend/components/google/drive/list/GoogleDriveListProperties.java
  components/components-googledrive/components-googledrive-definition/src/main/java/org/talend/components/google/drive/put/GoogleDrivePutProperties.java
  components/components-googledrive/components-googledrive-definition/src/main/resources/org/talend/components/google/drive/list/messages.properties
  components/components-googledrive/components-googledrive-definition/src/main/resources/org/talend/components/google/drive/messages.properties
  components/components-googledrive/components-googledrive-definition/src/main/resources/org/talend/components/google/drive/put/messages.properties
  components/components-googledrive/components-googledrive-integration/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveListTestIT.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveAbstractListReader.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveConstants.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveCopyReader.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveCopyRuntime.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveCreateReader.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveCreateRuntime.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveDeleteReader.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveDeleteRuntime.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveGetReader.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveGetRuntime.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveListReader.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDrivePutReader.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDrivePutRuntime.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDrivePutWriter.java
  components/components-googledrive/components-googledrive-runtime/src/main/java/org/talend/components/google/drive/runtime/GoogleDriveUtils.java
  components/components-googledrive/components-googledrive-runtime/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveCopyReaderTest.java
  components/components-googledrive/components-googledrive-runtime/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveCopyRuntimeTest.java
  components/components-googledrive/components-googledrive-runtime/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveCreateReaderTest.java
  components/components-googledrive/components-googledrive-runtime/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveCreateRuntimeTest.java
  components/components-googledrive/components-googledrive-runtime/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveDeleteReaderTest.java
  components/components-googledrive/components-googledrive-runtime/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveDeleteRuntimeTest.java
  components/components-googledrive/components-googledrive-runtime/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveGetReaderTest.java
  components/components-googledrive/components-googledrive-runtime/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveGetRuntimeTest.java
  components/components-googledrive/components-googledrive-runtime/src/test/java/org/talend/components/google/drive/runtime/GoogleDriveListReaderTest.java
  components/components-googledrive/components-googledrive-runtime/src/test/java/org/talend/components/google/drive/runtime/GoogleDrivePutReaderTest.java
  components/components-googledrive/components-googledrive-runtime/src/test/java/org/talend/components/google/drive/runtime/GoogleDrivePutRuntimeTest.java
  components/components-googledrive/components-googledrive-runtime/src/test/java/org/talend/components/google/drive/runtime/GoogleDrivePutWriterTest.java
  components/components-googledrive/components-googledrive-runtime/src/test/java/org/talend/components/google/drive/runtime/data/GoogleDriveInputReaderTest.java
Labels: Merged build failed

#1715 TDI-44682 - Fix some locale issues
  components/components-jdbc/components-jdbc-definition/src/main/java/org/talend/components/jdbc/query/EDatabaseTypeName.java
Labels: Merged build passed

#1962 fix(TDI-46734): use talendcsv replace javacsv
  components-parent/components-bom/pom.xml
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/JDBCBulkFileWriter.java
  components/components-jdbc/components-jdbc-runtime/src/main/java/org/talend/components/jdbc/runtime/type/BulkFormatter.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/BulkResultSet.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/SalesforceBulkRuntime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/SalesforceBulkQueryV2Runtime.java
  components/components-salesforce/components-salesforce-runtime/src/main/java/org/talend/components/salesforce/runtime/bulk/v2/SalesforceBulkV2Runtime.java
  components/components-salesforce/components-salesforce-runtime/src/test/java/org/talend/components/salesforce/BulkResultSetTest.java
  core/components-common/pom.xml
  core/components-common/src/main/java/org/talend/components/common/runtime/BulkFileWriter.java
Labels: Merged build failed

#1964 feat(TDI-44605):Upgrade Salesforce Components to support Endpoint Version 52(latest)
  components-parent/components-bom/pom.xml
  components/components-salesforce/components-salesforce-definition/src/main/java/org/talend/components/salesforce/SalesforceConnectionProperties.java
  components/components-salesforce/components-salesforce-integration/src/test/java/org/talend/components/salesforce/integration/SalesforceComponentTestIT.java
  components/components-salesforce/components-salesforce-runtime/pom.xml
Labels: Merged build failed, Need review

#1972 chore(TDI-46859): Add license to the root pom
  pom.xml
Labels: Merged build failed, Need review
