Repository Talend/components, pull requests merged in 2021-05, with the labels that each got.

#1910 chore(TDI-45882): bump cxf version to 3.3.10
  components-parent/components-bom/pom.xml
  components-parent/pom.xml
Labels: Merged build passed

#1905 fix(TDI-45824): Bump jersey for tcompv0
  components-parent/components-bom/pom.xml
Labels: Merged build passed, Need review

#1918 fix(TDI-43757): Upgrade Apache Hadoop
  components-parent/components-bom/pom.xml
  core/components-adapter-beam-parent/pom.xml
Labels: Merged build failed

#1923 fix(TDI-45796): Fix log messages for Marklogic external mlcp
  components/components-marklogic/components-marklogic-runtime/src/main/java/org/talend/components/marklogic/runtime/bulkload/MarkLogicExternalBulkLoadRunner.java
Labels: Merged build passed, Need review

#1926 fix(TDI-46314): Exclude jetty-server from mlcp
  components/components-marklogic/components-marklogic-runtime/pom.xml
Labels: Merged build failed, Need review
