Repository Talend/components, pull requests merged in 2022-09, with the labels that each got.

#2111 fix(TDI-TDI-48307): CVE on Jetty-io library.
  components-parent/components-bom/pom.xml
Labels: Need review

#2119 fix(TDI-48307): BP_801: CVE on Jetty-io library.
  components-parent/components-bom/pom.xml
Labels: backport

#2123 fix(TDI-48470):OS Command Injection in Talend/components (master)CVE-2022-25168:hadoop-common:3.2.3
  components-parent/components-bom/pom.xml
  core/components-adapter-beam-parent/pom.xml
Labels: Need review

#2118 fix(TDI-48318): CVE for netty-common.
  components-parent/components-bom/pom.xml
Labels: Need review

#2135 fix(TDI-48318): CVE for netty-common. (#2118)
  components-parent/components-bom/pom.xml
Labels: Need review, backport
